/** Biblioteca gastronômica: 41 receitas oficiais, sincronizada com database/seed-data.json. */
import type { DietKey } from "./diets";
import type { ProductDiet } from "./dietCompatibility";

export type Moment = "cafe" | "almoco" | "jantar" | "lanche";
export type RecipeCategory = "tradicional";

export interface Recipe {
  slug: string;
  title: string;
  featuredHandle: string;
  compatibleDiets: DietKey[];
  moment: Moment;
  profile: ProductDiet["profile"];
  category?: RecipeCategory;
  intro: string;
  ingredients: string[];
  steps: string[];
  whyItWorks: string;
  substitution: string;
  hero: { color: string };
  subtitle?: string;
  chefWord?: string;
  time?: string;
  serves?: string;
  difficulty?: "Fácil" | "Médio" | "Avançado";
  harmonization?: string[];
  proteinaPrincipal?: Protein;
  dish?: { src: string; alt: string };
  relatedSlugs?: string[];
}

export const MOMENTS: Record<Moment, string> = {
  cafe: "Café da manhã",
  almoco: "Almoço",
  jantar: "Jantar",
  lanche: "Lanche",
};

export const CATEGORIES: Record<RecipeCategory, { label: string; short: string }> = {
  tradicional: { label: "Mesa de Todos — Tradicional", short: "Tradicional" },
};

/** 41 receitas oficiais do rebrand MASTER-MAX (fonte: MANUAL-RECEITAS.md). Não editar à mão. */
export const RECIPES: Recipe[] = [
  {
    slug: "omelete-cremoso-temperaflix-ervas-finas",
    title: "Omelete Cremoso com Temperaflix Ervas Finas",
    subtitle: "Um omelete dourado por fora e cremoso por dentro, recheado com cogumelos salteados, pimentão vermelho e queijo derretido.",
    intro: "Um omelete dourado por fora e cremoso por dentro, recheado com cogumelos salteados, pimentão vermelho e queijo derretido. O Temperaflix Ervas Finas entra na massa e na finalização, perfumando cada garfada. Café da manhã de hotel, feito em casa em 20 minutos.",
    featuredHandle: "temperaflix-ervas-finas",
    compatibleDiets: [],
    moment: "cafe",
    profile: "ervas",
    category: "tradicional",
    time: "20 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["4 ovos", "2 colheres (sopa) de creme de leite fresco", "1 colher (sopa) de manteiga", "100 g de cogumelos-de-paris fatiados", "1/2 pimentão vermelho em tiras finas", "60 g de queijo muçarela ralado", "1 colher (chá) de Temperaflix Ervas Finas Temperanzza, e mais a gosto para finalizar", "Sal a gosto"],
    steps: ["Em uma frigideira média, derreta metade da manteiga em fogo médio e salteie os cogumelos e o pimentão por 4 minutos, até dourarem. Tempere com uma pitada de sal e reserve.", "Em uma tigela, bata os ovos com o creme de leite, uma pitada de sal e metade do Temperaflix Ervas Finas até ficar homogêneo.", "Na mesma frigideira, derreta o restante da manteiga em fogo baixo e despeje os ovos. Cozinhe por 3 a 4 minutos, puxando as bordas para o centro, até a base firmar e o topo continuar cremoso.", "Distribua os cogumelos, o pimentão e o queijo sobre metade do omelete.", "Dobre o omelete ao meio, tampe a frigideira e deixe por 1 minuto para o queijo derreter.", "Transfira para o prato e finalize com o restante do Temperaflix Ervas Finas por cima."],
    chefWord: "Fogo baixo é o segredo da cremosidade: se o omelete dourar rápido demais, fica seco por dentro.",
    whyItWorks: "Fogo baixo é o segredo da cremosidade: se o omelete dourar rápido demais, fica seco por dentro.",
    substitution: "Troque os cogumelos por espinafre refogado ou tomate-cereja para variar o recheio.",
    proteinaPrincipal: "ovo",
    dish: { src: "/receitas/omelete-cremoso-temperaflix-ervas-finas.jpg", alt: "Omelete Cremoso com Temperaflix Ervas Finas — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "petiscos-temperaflix-ervas-finas",
    title: "Petiscos com Temperaflix Ervas Finas",
    subtitle: "Uma mesa de petiscos para dividir: batata frita crocante, iscas de frango empanadas, cogumelos salteados com castanhas e pipoca, tudo com o mesmo tempero.",
    intro: "Uma mesa de petiscos para dividir: batata frita crocante, iscas de frango empanadas, cogumelos salteados com castanhas e pipoca, tudo com o mesmo tempero. O Temperaflix Ervas Finas une os quatro sabores em uma só assinatura. Ideal para receber os amigos ou para a sessão de cinema em casa.",
    featuredHandle: "temperaflix-ervas-finas",
    compatibleDiets: [],
    moment: "lanche",
    profile: "ervas",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["4 batatas grandes cortadas em palitos", "500 g de filé de frango em iscas", "2 ovos batidos", "1 xícara de farinha panko", "200 g de cogumelos-de-paris cortados ao meio", "1/2 xícara de castanhas mistas (caju e amêndoas)", "1/2 xícara de milho de pipoca", "2 colheres (sopa) de manteiga", "2 colheres (sopa) de Temperaflix Ervas Finas Temperanzza", "Óleo para fritar", "Sal a gosto"],
    steps: ["Tempere as iscas de frango com sal e 1 colher (chá) de Temperaflix Ervas Finas. Passe no ovo batido e depois na farinha panko, pressionando bem.", "Aqueça o óleo a 170 °C e frite as batatas em porções por cerca de 6 minutos, até dourarem. Escorra em papel-toalha e polvilhe Temperaflix Ervas Finas ainda quentes.", "No mesmo óleo, frite as iscas de frango por 4 a 5 minutos, até dourarem por igual. Escorra em papel-toalha.", "Em uma frigideira, derreta 1 colher (sopa) de manteiga e salteie os cogumelos e as castanhas por 5 minutos. Tempere com Temperaflix Ervas Finas.", "Estoure a pipoca em uma panela tampada com um fio de óleo, em fogo médio. Regue com o restante da manteiga derretida, polvilhe Temperaflix Ervas Finas, tampe e sacuda a panela.", "Monte tudo em uma tábua ou travessa e sirva na hora."],
    chefWord: "Tempere a batata e a pipoca assim que saírem do fogo: o calor e a gordura ajudam o tempero a grudar.",
    whyItWorks: "Tempere a batata e a pipoca assim que saírem do fogo: o calor e a gordura ajudam o tempero a grudar.",
    substitution: "Na airfryer, asse as batatas e as iscas a 200 °C por 18 a 20 minutos, virando na metade do tempo.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/petiscos-temperaflix-ervas-finas.jpg", alt: "Petiscos com Temperaflix Ervas Finas — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "petiscos-gourmet-temperaflix-sabor-bacon",
    title: "Petiscos Gourmet com Temperaflix Sabor Bacon",
    subtitle: "A tábua de petiscos da casa em versão defumada: batata frita, frango empanado, cogumelos com castanhas e pipoca, todos com o mesmo tempero.",
    intro: "A tábua de petiscos da casa em versão defumada: batata frita, frango empanado, cogumelos com castanhas e pipoca, todos com o mesmo tempero. O Temperaflix Sabor Bacon leva o sabor de bacon a cada porção, sem precisar fritar uma fatia sequer. Para quem gosta de petisco com personalidade.",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "lanche",
    profile: "defumado",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["4 batatas grandes cortadas em palitos", "500 g de filé de frango em pedaços", "2 ovos batidos", "1 xícara de farinha panko", "200 g de cogumelos-de-paris cortados ao meio", "1/2 xícara de castanhas mistas (caju e amêndoas)", "1/2 xícara de milho de pipoca", "2 colheres (sopa) de manteiga", "2 colheres (sopa) de Temperaflix Sabor Bacon Temperanzza", "Óleo para fritar", "Sal a gosto"],
    steps: ["Tempere o frango com sal e 1 colher (chá) de Temperaflix Sabor Bacon. Passe no ovo batido e depois na farinha panko, pressionando bem.", "Aqueça o óleo a 170 °C e frite as batatas em porções por cerca de 6 minutos, até dourarem. Escorra e polvilhe Temperaflix Sabor Bacon ainda quentes.", "No mesmo óleo, frite o frango por 4 a 5 minutos, até dourar por igual. Escorra em papel-toalha.", "Em uma frigideira, derreta 1 colher (sopa) de manteiga e salteie os cogumelos e as castanhas por 5 minutos. Tempere com Temperaflix Sabor Bacon.", "Estoure a pipoca em uma panela tampada com um fio de óleo. Regue com o restante da manteiga derretida, polvilhe Temperaflix Sabor Bacon, tampe e sacuda a panela.", "Monte tudo em uma tábua ou travessa e sirva na hora."],
    chefWord: "Prove antes de acrescentar sal: o tempero já garante bastante sabor.",
    whyItWorks: "Prove antes de acrescentar sal: o tempero já garante bastante sabor.",
    substitution: "Sirva com maionese caseira misturada a uma pitada de Temperaflix Sabor Bacon para mergulhar as batatas.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/petiscos-gourmet-temperaflix-sabor-bacon.jpg", alt: "Petiscos Gourmet com Temperaflix Sabor Bacon — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ovos-benedict-temperaflix-sabor-bacon",
    title: "Ovos Benedict com Temperaflix Sabor Bacon",
    subtitle: "O clássico do brunch montado em camadas: pão tostado, bacon crocante, ovo pochê e molho holandês cremoso.",
    intro: "O clássico do brunch montado em camadas: pão tostado, bacon crocante, ovo pochê e molho holandês cremoso. O Temperaflix Sabor Bacon tempera o molho e reforça o sabor defumado. Acompanhado de folhas verdes para equilibrar.",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "cafe",
    profile: "defumado",
    category: "tradicional",
    time: "35 min",
    serves: "2 porções",
    difficulty: "Médio",
    ingredients: ["Para a montagem:", "2 muffins ingleses (ou 4 fatias grossas de pão de fôrma)", "4 fatias de bacon", "4 ovos bem frescos", "1 colher (sopa) de vinagre branco", "1 xícara de folhas verdes (rúcula e alface)", "Cebolinha picada para finalizar", "Para o molho holandês:", "2 gemas", "80 g de manteiga derretida", "1 colher (sopa) de suco de limão", "1 colher (chá) de Temperaflix Sabor Bacon Temperanzza", "Sal a gosto"],
    steps: ["Doure o bacon em uma frigideira até ficar crocante. Reserve e guarde a gordura na frigideira.", "Prepare o molho: em banho-maria, bata as gemas com o suco de limão até engrossarem levemente. Sem parar de bater, junte a manteiga derretida em fio até formar um creme liso. Tempere com sal e metade do Temperaflix Sabor Bacon.", "Abra os muffins ao meio e toste na gordura do bacon.", "Ferva água com o vinagre em uma panela. Abaixe o fogo, faça um redemoinho com uma colher e coloque um ovo por vez. Cozinhe por 3 minutos e retire com escumadeira.", "Monte: pão, bacon, ovo pochê e molho holandês por cima.", "Finalize com o restante do Temperaflix Sabor Bacon e a cebolinha. Sirva com as folhas verdes."],
    chefWord: "Use ovos bem frescos: a clara fica firme e o pochê não se desfaz na água.",
    whyItWorks: "Use ovos bem frescos: a clara fica firme e o pochê não se desfaz na água.",
    substitution: "Se o molho talhar, junte 1 colher (sopa) de água quente e bata vigorosamente até voltar a ficar liso.",
    proteinaPrincipal: "ovo",
    dish: { src: "/receitas/ovos-benedict-temperaflix-sabor-bacon.jpg", alt: "Ovos Benedict com Temperaflix Sabor Bacon — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "omelete-de-bacon-temperaflix-sabor-bacon",
    title: "Omelete de Bacon com Temperaflix Sabor Bacon",
    subtitle: "Omelete dourado, recheado com bacon crocante e queijo derretido que escorre ao cortar.",
    intro: "Omelete dourado, recheado com bacon crocante e queijo derretido que escorre ao cortar. O Temperaflix Sabor Bacon vai na massa e por cima, dobrando o sabor defumado. Pronto em 20 minutos, sem pão e sem complicação.",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "cafe",
    profile: "defumado",
    category: "tradicional",
    time: "20 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["4 ovos", "100 g de bacon em cubos", "80 g de queijo muçarela ralado", "1 colher (sopa) de manteiga", "1 colher (chá) de Temperaflix Sabor Bacon Temperanzza", "Sal a gosto"],
    steps: ["Doure o bacon em uma frigideira antiaderente até ficar crocante. Retire e descarte o excesso de gordura.", "Bata os ovos com uma pitada de sal e metade do Temperaflix Sabor Bacon.", "Derreta a manteiga na frigideira em fogo baixo e despeje os ovos. Cozinhe por 3 minutos, até a base firmar.", "Espalhe o bacon e o queijo sobre metade do omelete.", "Dobre ao meio, tampe e deixe por 1 minuto para o queijo derreter.", "Sirva polvilhado com o restante do Temperaflix Sabor Bacon."],
    chefWord: "Para uma casquinha mais dourada, deixe o omelete em fogo médio por 30 segundos antes de servir.",
    whyItWorks: "Para uma casquinha mais dourada, deixe o omelete em fogo médio por 30 segundos antes de servir.",
    substitution: "Acrescente tomate picado ou cebolinha ao recheio para mais frescor.",
    proteinaPrincipal: "ovo",
    dish: { src: "/receitas/omelete-de-bacon-temperaflix-sabor-bacon.jpg", alt: "Omelete de Bacon com Temperaflix Sabor Bacon — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "hamburguer-bacon-queijo-temperaflix-sabor-bacon",
    title: "Hambúrguer Bacon com Queijo e Temperaflix Sabor Bacon",
    subtitle: "Hambúrguer artesanal alto e suculento, com cheddar derretido, bacon crocante e tomate no pão brioche.",
    intro: "Hambúrguer artesanal alto e suculento, com cheddar derretido, bacon crocante e tomate no pão brioche. O Temperaflix Sabor Bacon tempera a carne antes de ir para a chapa. O queijo escorre, o shaker assina.",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "lanche",
    profile: "defumado",
    category: "tradicional",
    time: "27 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["600 g de carne moída (acém ou fraldinha, com 20% de gordura)", "8 fatias de bacon", "4 fatias de queijo cheddar", "4 pães brioche", "1 tomate em rodelas", "1 colher (sopa) de manteiga", "1 colher (sopa) de Temperaflix Sabor Bacon Temperanzza", "Sal e pimenta-do-reino a gosto"],
    steps: ["Divida a carne em 4 porções de 150 g e modele discos 1 cm mais largos que o pão, sem apertar demais.", "Tempere os dois lados de cada hambúrguer com Temperaflix Sabor Bacon, sal e pimenta-do-reino.", "Doure o bacon em uma chapa ou frigideira grande até ficar crocante. Reserve.", "Na mesma chapa bem quente, grelhe os hambúrgueres por 3 a 4 minutos de cada lado. No último minuto, coloque o cheddar e tampe para derreter.", "Toste os pães abertos na manteiga.", "Monte: pão, hambúrguer com cheddar, bacon, tomate e a tampa do pão."],
    chefWord: "Faça uma leve depressão no centro do disco com o polegar: assim o hambúrguer não estufa na chapa.",
    whyItWorks: "Faça uma leve depressão no centro do disco com o polegar: assim o hambúrguer não estufa na chapa.",
    substitution: "Vire a carne uma única vez para manter a crosta e a suculência.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/hamburguer-bacon-queijo-temperaflix-sabor-bacon.jpg", alt: "Hambúrguer Bacon com Queijo e Temperaflix Sabor Bacon — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-ensopado-ana-maria",
    title: "Frango Ensopado com Ana Maria",
    subtitle: "Coxas e sobrecoxas cozidas devagar em um caldo encorpado com cenoura e batata.",
    intro: "Coxas e sobrecoxas cozidas devagar em um caldo encorpado com cenoura e batata. O Ana Maria tempera o frango desde o início e dá cor ao molho. Comida de panela, conforto em forma de refogado.",
    featuredHandle: "ana-maria",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "60 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1 kg de coxas e sobrecoxas de frango", "1 cebola picada", "2 dentes de alho picados", "2 tomates picados", "1 cenoura em rodelas", "2 batatas em cubos", "2 colheres (sopa) de azeite", "1 colher (sopa) de Ana Maria Temperanzza", "500 ml de água quente", "Sal a gosto", "Cheiro-verde picado para finalizar"],
    steps: ["Tempere o frango com o Ana Maria e sal. Deixe descansar por 15 minutos.", "Em uma panela, aqueça o azeite e doure os pedaços de frango de todos os lados. Retire e reserve.", "Na mesma panela, refogue a cebola e o alho até ficarem transparentes. Junte o tomate e cozinhe até desmanchar.", "Volte o frango à panela, adicione a água quente, tampe e cozinhe em fogo baixo por 25 minutos.", "Acrescente a cenoura e a batata e cozinhe por mais 15 minutos, até os legumes ficarem macios e o caldo encorpar.", "Acerte o sal e finalize com cheiro-verde."],
    chefWord: "Dourar bem o frango antes de ensopar é o que dá cor e profundidade ao caldo.",
    whyItWorks: "Dourar bem o frango antes de ensopar é o que dá cor e profundidade ao caldo.",
    substitution: "Sirva com arroz branco e angu para a mesa mineira completa.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/frango-ensopado-ana-maria.jpg", alt: "Frango Ensopado com Ana Maria — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-grelhado-ana-maria",
    title: "Frango Grelhado com Ana Maria",
    subtitle: "Filé de peito de frango suculento, com marcas de grelha e tempero na medida.",
    intro: "Filé de peito de frango suculento, com marcas de grelha e tempero na medida. O Ana Maria faz o frango simples parecer almoço de domingo. Uma base versátil para o almoço, a marmita ou a salada.",
    featuredHandle: "ana-maria",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "40 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["2 filés de peito de frango (cerca de 400 g)", "1 colher (sopa) de azeite", "Suco de 1/2 limão", "2 colheres (chá) de Ana Maria Temperanzza", "Sal a gosto"],
    steps: ["Abra os filés ao meio no sentido da espessura, para que fiquem com altura uniforme.", "Tempere com o Ana Maria, o suco de limão, o azeite e sal. Deixe marinar por pelo menos 20 minutos.", "Aqueça bem uma grelha ou frigideira de ferro em fogo alto.", "Grelhe os filés por 4 a 5 minutos de cada lado, sem mexer, até formar as marcas e o centro ficar cozido.", "Deixe descansar por 3 minutos antes de servir ou fatiar."],
    chefWord: "Não mexa o filé enquanto grelha: as marcas só aparecem com contato firme e contínuo.",
    whyItWorks: "Não mexa o filé enquanto grelha: as marcas só aparecem com contato firme e contínuo.",
    substitution: "Se tiver tempo, deixe marinando por até 4 horas na geladeira para um sabor mais profundo.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/frango-grelhado-ana-maria.jpg", alt: "Frango Grelhado com Ana Maria — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ovos-cremosos-queijo-gratinado-temperaflix-tradicional",
    title: "Ovos Cremosos com Queijo Gratinado e Temperaflix Tradicional",
    subtitle: "Ovos mexidos em fogo baixo até ficarem cremosos, cobertos com queijo e levados ao forno para gratinar.",
    intro: "Ovos mexidos em fogo baixo até ficarem cremosos, cobertos com queijo e levados ao forno para gratinar. O Temperaflix Tradicional entra no final, sobre o queijo dourado. Um café da manhã rápido com cara de restaurante.",
    featuredHandle: "temperaflix-tradicional",
    compatibleDiets: [],
    moment: "cafe",
    profile: "casa",
    category: "tradicional",
    time: "15 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["5 ovos", "2 colheres (sopa) de requeijão cremoso", "1 colher (sopa) de manteiga", "60 g de queijo muçarela ralado", "2 colheres (sopa) de queijo parmesão ralado", "1 colher (chá) de Temperaflix Tradicional Temperanzza", "Sal a gosto", "Salsinha picada para finalizar"],
    steps: ["Preaqueça o forno a 220 °C, com a função grill se houver.", "Bata levemente os ovos com o requeijão e uma pitada de sal.", "Derreta a manteiga em fogo baixo, em uma frigideira que possa ir ao forno. Despeje os ovos e mexa devagar com uma espátula por 3 a 4 minutos, até formarem dobras cremosas.", "Desligue o fogo e cubra com a muçarela e o parmesão.", "Leve ao forno por 4 a 5 minutos, até o queijo borbulhar e dourar.", "Finalize com Temperaflix Tradicional e salsinha. Sirva na hora."],
    chefWord: "Tire os ovos do fogo ainda um pouco úmidos: eles terminam de cozinhar no forno.",
    whyItWorks: "Tire os ovos do fogo ainda um pouco úmidos: eles terminam de cozinhar no forno.",
    substitution: "Sem frigideira que vá ao forno? Transfira os ovos para um refratário antes de gratinar.",
    proteinaPrincipal: "ovo",
    dish: { src: "/receitas/ovos-cremosos-queijo-gratinado-temperaflix-tradicional.jpg", alt: "Ovos Cremosos com Queijo Gratinado e Temperaflix Tradicional — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "petiscos-temperaflix-tradicional",
    title: "Petiscos com Temperaflix Tradicional",
    subtitle: "Batata frita, frango empanado e uma tigela generosa de pipoca, tudo com o mesmo tempero.",
    intro: "Batata frita, frango empanado e uma tigela generosa de pipoca, tudo com o mesmo tempero. O Temperaflix Tradicional acompanha cada porção, do primeiro ao último petisco. O cinema em casa nunca foi tão bem temperado.",
    featuredHandle: "temperaflix-tradicional",
    compatibleDiets: [],
    moment: "lanche",
    profile: "casa",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["4 batatas grandes cortadas em palitos", "500 g de filé de frango em pedaços", "1 xícara de farinha de trigo", "2 ovos batidos", "1 xícara de farinha panko", "1/2 xícara de milho de pipoca", "2 colheres (sopa) de manteiga derretida", "2 colheres (sopa) de Temperaflix Tradicional Temperanzza", "Óleo para fritar", "Sal a gosto"],
    steps: ["Tempere o frango com sal e 1 colher (chá) de Temperaflix Tradicional. Passe na farinha de trigo, no ovo batido e na farinha panko, nessa ordem.", "Aqueça o óleo a 170 °C e frite as batatas em porções por cerca de 6 minutos, até dourarem. Escorra e polvilhe Temperaflix Tradicional ainda quentes.", "No mesmo óleo, frite o frango por 4 a 5 minutos, até dourar por igual. Escorra em papel-toalha.", "Estoure a pipoca em uma panela tampada com um fio de óleo. Regue com a manteiga derretida, polvilhe Temperaflix Tradicional, tampe e sacuda a panela.", "Sirva tudo junto em uma tábua ou travessa."],
    chefWord: "Empane o frango com antecedência e deixe 15 minutos na geladeira: a casquinha fica mais firme na fritura.",
    whyItWorks: "Empane o frango com antecedência e deixe 15 minutos na geladeira: a casquinha fica mais firme na fritura.",
    substitution: "Sacudir a panela tampada depois de colocar o tempero deixa a pipoca temperada por igual.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/petiscos-temperaflix-tradicional.jpg", alt: "Petiscos com Temperaflix Tradicional — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ensopado-rustico-tempero-mineiro",
    title: "Ensopado Rústico com Tempero Mineiro",
    subtitle: "Pedaços de carne cozidos lentamente até desmanchar, com batatas inteiras em um molho escuro e brilhante.",
    intro: "Pedaços de carne cozidos lentamente até desmanchar, com batatas inteiras em um molho escuro e brilhante. O Tempero Mineiro dá a base de fundo de quintal que esse prato pede. O prato de domingo, todo dia.",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "110 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["1,2 kg de acém ou músculo em cubos grandes", "500 g de batatas pequenas descascadas", "1 cebola picada", "3 dentes de alho picados", "2 colheres (sopa) de extrato de tomate", "2 colheres (sopa) de óleo", "1 colher (sopa) de Tempero Mineiro Temperanzza", "2 folhas de louro", "1 litro de água quente", "Sal a gosto"],
    steps: ["Tempere a carne com o Tempero Mineiro e sal.", "Na panela de pressão aberta, aqueça o óleo e sele a carne em porções até dourar bem. Retire e reserve.", "Refogue a cebola e o alho na mesma panela. Junte o extrato de tomate e mexa por 2 minutos.", "Volte a carne à panela, junte o louro e a água quente. Tampe e cozinhe por 40 minutos após pegar pressão (ou 1h45 em panela comum tampada).", "Retire a pressão, junte as batatas e cozinhe com a panela aberta por 20 minutos, até as batatas ficarem macias e o molho encorpar.", "Retire o louro e acerte o sal."],
    chefWord: "Selar a carne em porções pequenas evita que ela solte água e garante a cor escura do molho.",
    whyItWorks: "Selar a carne em porções pequenas evita que ela solte água e garante a cor escura do molho.",
    substitution: "Fica ainda melhor no dia seguinte: o molho apura e os sabores se integram.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/ensopado-rustico-tempero-mineiro.jpg", alt: "Ensopado Rústico com Tempero Mineiro — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "feijao-tropeiro-tempero-mineiro",
    title: "Feijão Tropeiro com Tempero Mineiro",
    subtitle: "Feijão firme, bacon, linguiça, ovos e farinha de mandioca, tudo misturado na panela quente.",
    intro: "Feijão firme, bacon, linguiça, ovos e farinha de mandioca, tudo misturado na panela quente. O Tempero Mineiro é a nossa homenagem a esse clássico de fundo de quintal. Tradição mineira, do jeito que deve ser.",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["3 xícaras de feijão carioca cozido al dente e bem escorrido", "150 g de bacon em cubos", "1 linguiça calabresa em cubos", "2 ovos", "1 cebola picada", "2 dentes de alho picados", "1 xícara de farinha de mandioca", "1 colher (sopa) de Tempero Mineiro Temperanzza", "Cebolinha picada a gosto", "Sal a gosto"],
    steps: ["Em uma panela grande, frite o bacon e a linguiça até dourarem e soltarem gordura. Retire e reserve, deixando a gordura na panela.", "Mexa os ovos na gordura até firmarem. Retire e reserve.", "Refogue a cebola e o alho até ficarem dourados.", "Junte o feijão e o Tempero Mineiro e refogue por 3 minutos.", "Adicione a farinha de mandioca aos poucos, sempre mexendo.", "Volte o bacon, a linguiça e os ovos à panela, acerte o sal e finalize com cebolinha."],
    chefWord: "O feijão precisa estar bem escorrido e firme: feijão com caldo deixa o tropeiro empapado.",
    whyItWorks: "O feijão precisa estar bem escorrido e firme: feijão com caldo deixa o tropeiro empapado.",
    substitution: "Sirva com couve refogada, arroz branco e torresmo para o combo mineiro completo.",
    proteinaPrincipal: "suino",
    dish: { src: "/receitas/feijao-tropeiro-tempero-mineiro.jpg", alt: "Feijão Tropeiro com Tempero Mineiro — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "pao-de-queijo-tempero-mineiro",
    title: "Pão de Queijo com Tempero Mineiro",
    subtitle: "Pão de queijo com casquinha dourada e miolo macio, com o perfume do Tempero Mineiro na massa.",
    intro: "Pão de queijo com casquinha dourada e miolo macio, com o perfume do Tempero Mineiro na massa. A receita de polvilho escaldado de sempre, com um toque que só a Temperanzza tem. A tradição mineira, com a alma da casa.",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "cafe",
    profile: "casa",
    category: "tradicional",
    time: "45 min",
    serves: "30 unidades",
    difficulty: "Médio",
    ingredients: ["500 g de polvilho azedo", "1 xícara de leite", "1/2 xícara de óleo", "1 colher (chá) de sal", "2 ovos", "200 g de queijo meia cura ralado", "50 g de queijo parmesão ralado", "2 colheres (chá) de Tempero Mineiro Temperanzza"],
    steps: ["Preaqueça o forno a 180 °C.", "Ferva o leite, o óleo e o sal. Despeje sobre o polvilho e mexa até esfarelar. Deixe amornar.", "Acrescente os ovos, um de cada vez, sovando bem a cada adição.", "Junte os queijos e o Tempero Mineiro e sove até a massa ficar lisa e desgrudar das mãos.", "Com as mãos untadas, faça bolinhas de 3 cm e distribua em uma assadeira, com espaço entre elas.", "Asse por 25 a 30 minutos, até dourarem."],
    chefWord: "Se a massa ficar mole demais, acrescente polvilho às colheradas; se ficar seca, um pouco de leite.",
    whyItWorks: "Se a massa ficar mole demais, acrescente polvilho às colheradas; se ficar seca, um pouco de leite.",
    substitution: "Congele as bolinhas cruas em uma assadeira e depois guarde em saco: elas vão ao forno direto do freezer, com 5 minutos a mais.",
    proteinaPrincipal: "paes",
    dish: { src: "/receitas/pao-de-queijo-tempero-mineiro.jpg", alt: "Pão de Queijo com Tempero Mineiro — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "berinjela-recheada-tempero-mineiro",
    title: "Berinjela Recheada com Tempero Mineiro",
    subtitle: "Berinjelas assadas e recheadas com carne moída, pimentões e tomate, gratinadas até dourar.",
    intro: "Berinjelas assadas e recheadas com carne moída, pimentões e tomate, gratinadas até dourar. O Tempero Mineiro dá corpo ao recheio e transforma o legume em prato principal. Uma assadeira só, do forno para a mesa.",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "jantar",
    profile: "casa",
    category: "tradicional",
    time: "55 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["4 berinjelas médias", "300 g de carne moída", "1 cebola picada", "2 dentes de alho picados", "1 pimentão vermelho em cubos", "1 pimentão amarelo em cubos", "2 tomates picados", "80 g de queijo muçarela ralado", "2 colheres (sopa) de azeite", "1 colher (sopa) de Tempero Mineiro Temperanzza", "Sal a gosto"],
    steps: ["Preaqueça o forno a 200 °C. Corte as berinjelas ao meio no comprimento, faça cortes em xadrez na polpa, regue com azeite, tempere com sal e asse por 15 minutos com a polpa para cima.", "Com uma colher, retire parte da polpa, deixando uma borda de 1 cm. Pique a polpa retirada.", "Em uma frigideira, refogue a cebola e o alho no azeite. Junte a carne moída e cozinhe até soltar e dourar. Tempere com o Tempero Mineiro.", "Acrescente os pimentões, o tomate e a polpa picada e cozinhe por 8 minutos. Acerte o sal.", "Recheie as berinjelas, cubra com a muçarela e asse por 15 a 20 minutos, até gratinar."],
    chefWord: "Os cortes em xadrez ajudam a berinjela a assar por igual e facilitam a retirada da polpa.",
    whyItWorks: "Os cortes em xadrez ajudam a berinjela a assar por igual e facilitam a retirada da polpa.",
    substitution: "Para uma versão vegetariana, troque a carne por cogumelos picados.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/berinjela-recheada-tempero-mineiro.jpg", alt: "Berinjela Recheada com Tempero Mineiro — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "carne-moida-tempero-mineiro",
    title: "Carne Moída com Tempero Mineiro",
    subtitle: "Carne moída bem dourada, soltinha e temperada de uma vez, na frigideira de ferro.",
    intro: "Carne moída bem dourada, soltinha e temperada de uma vez, na frigideira de ferro. O Tempero Mineiro resolve o sabor sem precisar de mais nada. A base de metade dos almoços da semana.",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "30 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["600 g de carne moída (patinho ou acém)", "1 cebola picada", "2 dentes de alho picados", "1 colher (sopa) de óleo", "1 colher (sopa) de Tempero Mineiro Temperanzza", "Sal a gosto", "Cheiro-verde picado a gosto"],
    steps: ["Aqueça muito bem uma frigideira de ferro com o óleo, em fogo alto.", "Espalhe a carne na frigideira e deixe por 3 minutos sem mexer, para dourar.", "Mexa, soltando a carne com uma espátula, por cerca de 8 minutos, até secar a água e dourar por igual.", "Junte a cebola e o alho e refogue por 3 minutos.", "Adicione o Tempero Mineiro e o sal e cozinhe por mais 2 minutos.", "Finalize com cheiro-verde."],
    chefWord: "Use fogo alto e uma panela grande: carne amontoada cozinha no próprio vapor e não doura.",
    whyItWorks: "Use fogo alto e uma panela grande: carne amontoada cozinha no próprio vapor e não doura.",
    substitution: "Use como recheio de panqueca, torta ou berinjela, ou sirva com arroz e ovo frito.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/carne-moida-tempero-mineiro.jpg", alt: "Carne Moída com Tempero Mineiro — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "costela-paprica-defumada",
    title: "Costela com Páprica Defumada",
    subtitle: "Costela assada lentamente até soltar do osso, com casquinha escura e brilhante.",
    intro: "Costela assada lentamente até soltar do osso, com casquinha escura e brilhante. A Páprica Defumada dá o sabor de defumação sem precisar de defumador. Fogo baixo, paciência e resultado de churrascaria.",
    featuredHandle: "paprica-defumada",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "195 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["1,5 kg de costela bovina em ripas", "2 colheres (sopa) de Páprica Defumada Temperanzza", "1 colher (sopa) de sal grosso moído", "1 colher (sopa) de açúcar mascavo", "3 dentes de alho amassados", "2 colheres (sopa) de azeite", "3 colheres (sopa) de molho barbecue (opcional, para pincelar)"],
    steps: ["Misture a Páprica Defumada, o sal, o açúcar mascavo, o alho e o azeite até formar uma pasta. Esfregue em toda a costela e, se possível, deixe descansar por 2 horas na geladeira.", "Preaqueça o forno a 160 °C.", "Embrulhe a costela em papel-alumínio, com o lado brilhante para dentro, e asse por 2h30, até a carne ficar macia.", "Abra o papel-alumínio, pincele o molho barbecue, aumente o forno para 220 °C e asse por mais 20 a 30 minutos, até formar a casquinha.", "Deixe descansar por 10 minutos e corte entre os ossos."],
    chefWord: "O papel-alumínio segura o vapor e amacia a carne; a etapa final sem papel é o que cria a casquinha.",
    whyItWorks: "O papel-alumínio segura o vapor e amacia a carne; a etapa final sem papel é o que cria a casquinha.",
    substitution: "Aproveite o caldo que fica no papel-alumínio: reduza em uma panela e sirva como molho.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/costela-paprica-defumada.jpg", alt: "Costela com Páprica Defumada — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ensopado-de-carne-cozida-paprica-defumada",
    title: "Ensopado de Carne Cozida com Páprica Defumada",
    subtitle: "Carne em pedaços cozida no caldo com cenoura, batata e vagem, até ficar macia a ponto de desfiar.",
    intro: "Carne em pedaços cozida no caldo com cenoura, batata e vagem, até ficar macia a ponto de desfiar. A Páprica Defumada dá cor ao caldo e um fundo defumado que aquece. Um prato só, completo e reconfortante.",
    featuredHandle: "paprica-defumada",
    compatibleDiets: [],
    moment: "jantar",
    profile: "defumado",
    category: "tradicional",
    time: "110 min",
    serves: "6 porções",
    difficulty: "Fácil",
    ingredients: ["1 kg de músculo em cubos", "2 batatas em cubos", "2 cenouras em rodelas", "100 g de vagem em pedaços", "1 cebola picada", "3 dentes de alho picados", "2 tomates picados", "2 colheres (sopa) de azeite", "1 colher (sopa) de Páprica Defumada Temperanzza", "1,2 litro de água quente", "Sal a gosto", "Salsinha picada para finalizar"],
    steps: ["Tempere a carne com metade da Páprica Defumada e sal.", "Na panela de pressão aberta, aqueça o azeite e sele a carne em porções até dourar. Retire e reserve.", "Refogue a cebola, o alho e o tomate. Junte o restante da Páprica Defumada e mexa por 30 segundos.", "Volte a carne, junte a água quente, tampe e cozinhe por 35 minutos após pegar pressão (ou 1h30 em panela comum tampada).", "Retire a pressão, junte a batata, a cenoura e a vagem e cozinhe com a panela aberta por 15 a 20 minutos, até os legumes ficarem macios.", "Acerte o sal e finalize com salsinha."],
    chefWord: "Adicione a páprica com a panela em fogo médio: em fogo muito alto ela queima e amarga.",
    whyItWorks: "Adicione a páprica com a panela em fogo médio: em fogo muito alto ela queima e amarga.",
    substitution: "Sirva com pão rústico ou arroz branco para aproveitar o caldo.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/ensopado-de-carne-cozida-paprica-defumada.jpg", alt: "Ensopado de Carne Cozida com Páprica Defumada — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-assado-paprica-defumada",
    title: "Frango Assado com Páprica Defumada",
    subtitle: "Frango inteiro com pele dourada e crocante e carne suculenta por dentro.",
    intro: "Frango inteiro com pele dourada e crocante e carne suculenta por dentro. A Páprica Defumada dá cor e aroma de fogo lento, sem sair da cozinha. Um clássico de domingo que perfuma a casa toda.",
    featuredHandle: "paprica-defumada",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "95 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1 frango inteiro (cerca de 1,6 kg)", "3 colheres (sopa) de manteiga em temperatura ambiente", "2 colheres (sopa) de Páprica Defumada Temperanzza", "4 dentes de alho amassados", "Suco de 1 limão", "1 cebola cortada em quatro", "Sal a gosto"],
    steps: ["Seque bem o frango com papel-toalha, por dentro e por fora.", "Misture a manteiga, a Páprica Defumada, o alho, o suco de limão e o sal.", "Solte a pele do peito com os dedos e espalhe parte da pasta por baixo dela. Passe o restante por fora e por dentro do frango e coloque a cebola na cavidade.", "Deixe descansar por 30 minutos (ou de um dia para o outro na geladeira).", "Asse a 200 °C por 1h10 a 1h20, regando com o próprio caldo a cada 20 minutos, até dourar e o líquido sair claro ao espetar a coxa.", "Deixe descansar por 10 minutos antes de trinchar."],
    chefWord: "Secar bem a pele é o segredo da casquinha crocante.",
    whyItWorks: "Secar bem a pele é o segredo da casquinha crocante.",
    substitution: "Se a pele dourar antes do tempo, cubra com papel-alumínio e retire nos 15 minutos finais.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/frango-assado-paprica-defumada.jpg", alt: "Frango Assado com Páprica Defumada — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "hamburguer-pao-carnivoro-paprica-defumada",
    title: "Hambúrguer com Pão Carnívoro e Páprica Defumada",
    subtitle: "O sanduíche completo sem o peso do carboidrato: pão carnívoro dourado, hambúrguer suculento e queijo derretido.",
    intro: "O sanduíche completo sem o peso do carboidrato: pão carnívoro dourado, hambúrguer suculento e queijo derretido. A Páprica Defumada tempera a carne e o pão. Feito para quem segue a dieta low carb ou carnívora.",
    featuredHandle: "paprica-defumada",
    compatibleDiets: [],
    moment: "lanche",
    profile: "defumado",
    category: "tradicional",
    time: "60 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["Para o pão carnívoro:", "300 g de peito de frango cozido e desfiado", "3 ovos", "100 g de queijo muçarela ralado", "1 colher (chá) de fermento químico em pó", "Sal a gosto", "Para o hambúrguer:", "600 g de carne moída (com 20% de gordura)", "4 fatias de queijo cheddar", "Sal a gosto", "Tempero:", "2 colheres (sopa) de Páprica Defumada Temperanzza (1 colher de chá para o pão e o restante para a carne)"],
    steps: ["Preaqueça o forno a 180 °C e forre uma assadeira com papel-manteiga.", "Processe o frango, os ovos, a muçarela, o fermento, 1 colher (chá) de Páprica Defumada e o sal até formar uma massa homogênea.", "Com as mãos molhadas, modele 4 discos altos de 10 cm e asse por 25 minutos, até dourarem. Deixe esfriar por 5 minutos e abra ao meio.", "Modele 4 hambúrgueres de 150 g e tempere com o restante da Páprica Defumada e sal.", "Grelhe por 3 a 4 minutos de cada lado. No último minuto, coloque o cheddar e tampe para derreter.", "Monte o hambúrguer no pão carnívoro e sirva."],
    chefWord: "Com as mãos molhadas, a massa do pão, que é pegajosa, fica muito mais fácil de modelar.",
    whyItWorks: "Com as mãos molhadas, a massa do pão, que é pegajosa, fica muito mais fácil de modelar.",
    substitution: "Toste o pão aberto na frigideira por 1 minuto antes de montar para ele ganhar firmeza.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/hamburguer-pao-carnivoro-paprica-defumada.jpg", alt: "Hambúrguer com Pão Carnívoro e Páprica Defumada — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "camarao-paprica-picante",
    title: "Camarão com Páprica Picante",
    subtitle: "Camarões grandes salteados na frigideira de ferro até ganharem cor e brilho.",
    intro: "Camarões grandes salteados na frigideira de ferro até ganharem cor e brilho. A Páprica Picante traz calor equilibrado e uma cor vermelha intensa. Sofisticação em menos de 20 minutos, como petisco ou entrada.",
    featuredHandle: "paprica-picante",
    compatibleDiets: [],
    moment: "lanche",
    profile: "citrico-picante",
    category: "tradicional",
    time: "18 min",
    serves: "3 porções",
    difficulty: "Fácil",
    ingredients: ["500 g de camarão grande limpo, com cauda", "3 colheres (sopa) de azeite", "1 colher (sopa) de manteiga", "3 dentes de alho fatiados", "2 colheres (chá) de Páprica Picante Temperanzza", "Suco de 1/2 limão", "Sal a gosto", "Salsinha picada para finalizar"],
    steps: ["Seque bem os camarões e tempere com a Páprica Picante e sal.", "Aqueça o azeite em uma frigideira de ferro em fogo alto.", "Coloque os camarões em uma única camada e deixe por 2 minutos sem mexer. Vire e cozinhe por mais 1 a 2 minutos, até ficarem rosados.", "Abaixe o fogo, junte a manteiga e o alho e cozinhe por 1 minuto.", "Regue com o suco de limão, finalize com salsinha e sirva na própria frigideira."],
    chefWord: "Não cozinhe demais: o camarão passa do ponto em segundos e fica borrachudo.",
    whyItWorks: "Não cozinhe demais: o camarão passa do ponto em segundos e fica borrachudo.",
    substitution: "Sirva com pão rústico para mergulhar no molho de manteiga e páprica.",
    proteinaPrincipal: "pescados",
    dish: { src: "/receitas/camarao-paprica-picante.jpg", alt: "Camarão com Páprica Picante — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "costela-suina-paprica-picante",
    title: "Costela Suína com Páprica Picante",
    subtitle: "Costela suína em ripas assada devagar e finalizada em forno alto para caramelizar.",
    intro: "Costela suína em ripas assada devagar e finalizada em forno alto para caramelizar. A Páprica Picante pinta a carne de vermelho e traz um calor que acompanha cada mordida. Carne que solta do osso, com casquinha picante.",
    featuredHandle: "paprica-picante",
    compatibleDiets: [],
    moment: "almoco",
    profile: "citrico-picante",
    category: "tradicional",
    time: "160 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["1,5 kg de costela suína em ripas", "2 colheres (sopa) de Páprica Picante Temperanzza", "1 colher (sopa) de açúcar mascavo", "1 colher (sopa) de sal", "3 dentes de alho amassados", "Suco de 1 limão", "2 colheres (sopa) de mel"],
    steps: ["Retire a membrana branca do lado do osso da costela.", "Misture a Páprica Picante, o açúcar mascavo, o sal, o alho e o suco de limão. Esfregue em toda a costela e deixe descansar por 1 hora na geladeira.", "Preaqueça o forno a 170 °C. Embrulhe a costela em papel-alumínio e asse por 2 horas.", "Abra o papel, pincele o mel misturado com uma pitada de Páprica Picante, aumente o forno para 220 °C e asse por 20 a 25 minutos, até caramelizar.", "Deixe descansar por 10 minutos e corte entre os ossos."],
    chefWord: "Retirar a membrana do lado do osso deixa o tempero penetrar e a carne mais macia.",
    whyItWorks: "Retirar a membrana do lado do osso deixa o tempero penetrar e a carne mais macia.",
    substitution: "Para um calor mais suave, use metade de Páprica Picante e metade de Páprica Doce.",
    proteinaPrincipal: "suino",
    dish: { src: "/receitas/costela-suina-paprica-picante.jpg", alt: "Costela Suína com Páprica Picante — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "sardinhas-grelhadas-paprica-picante-salada",
    title: "Sardinhas Grelhadas com Páprica Picante e Salada",
    subtitle: "Sardinhas frescas grelhadas inteiras, com pele tostada e carne macia, servidas com limão e salada verde.",
    intro: "Sardinhas frescas grelhadas inteiras, com pele tostada e carne macia, servidas com limão e salada verde. A Páprica Picante dá cor e um calor leve que combina com o sabor marcante do peixe. Ômega-3 e frescor em uma refeição rápida.",
    featuredHandle: "paprica-picante",
    compatibleDiets: [],
    moment: "jantar",
    profile: "citrico-picante",
    category: "tradicional",
    time: "25 min",
    serves: "3 porções",
    difficulty: "Fácil",
    ingredients: ["Para as sardinhas:", "12 sardinhas frescas limpas (sem escamas e vísceras)", "3 colheres (sopa) de azeite", "2 colheres (chá) de Páprica Picante Temperanzza", "Sal grosso moído a gosto", "2 limões-sicilianos em gomos", "Para a salada:", "2 xícaras de folhas de alface e rúcula", "10 tomates-cereja cortados ao meio", "1/2 cebola roxa em fatias finas", "Azeite e sal a gosto"],
    steps: ["Seque as sardinhas, pincele com azeite e tempere por dentro e por fora com a Páprica Picante e sal.", "Aqueça uma grelha ou chapa untada em fogo alto.", "Grelhe as sardinhas por 3 a 4 minutos de cada lado, virando uma única vez com uma espátula larga.", "Monte a salada e tempere com azeite e sal.", "Sirva as sardinhas com os gomos de limão e a salada, com uma pitada de Páprica Picante por cima."],
    chefWord: "Grelha muito quente e pouco manuseio: assim a pele não gruda e as sardinhas ficam inteiras.",
    whyItWorks: "Grelha muito quente e pouco manuseio: assim a pele não gruda e as sardinhas ficam inteiras.",
    substitution: "Também ficam ótimas no forno a 230 °C por 12 a 15 minutos.",
    proteinaPrincipal: "pescados",
    dish: { src: "/receitas/sardinhas-grelhadas-paprica-picante-salada.jpg", alt: "Sardinhas Grelhadas com Páprica Picante e Salada — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "sopa-de-legumes-paprica-picante",
    title: "Sopa de Legumes com Páprica Picante",
    subtitle: "Sopa de legumes com caldo avermelhado, tomate, cenoura, batata e abobrinha.",
    intro: "Sopa de legumes com caldo avermelhado, tomate, cenoura, batata e abobrinha. A Páprica Picante aquece o caldo e dá cor, sem precisar de caldo pronto. Leve, nutritiva e perfeita para as noites frias.",
    featuredHandle: "paprica-picante",
    compatibleDiets: [],
    moment: "jantar",
    profile: "citrico-picante",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["2 colheres (sopa) de azeite", "1 cebola picada", "2 dentes de alho picados", "2 tomates picados", "1 cenoura em cubos", "1 batata em cubos", "1 abobrinha em cubos", "1 talo de salsão picado", "2 colheres (chá) de Páprica Picante Temperanzza", "1,2 litro de água quente", "Sal a gosto", "Salsinha e manjericão picados para finalizar"],
    steps: ["Em uma panela, refogue a cebola e o alho no azeite até ficarem macios.", "Junte a Páprica Picante e mexa por 30 segundos.", "Acrescente o tomate e cozinhe por 5 minutos, até desmanchar.", "Adicione a cenoura, a batata, o salsão e a água quente. Cozinhe por 15 minutos.", "Junte a abobrinha e cozinhe por mais 8 minutos.", "Acerte o sal e finalize com salsinha e manjericão."],
    chefWord: "Coloque a abobrinha por último: ela cozinha rápido e mantém a textura.",
    whyItWorks: "Coloque a abobrinha por último: ela cozinha rápido e mantém a textura.",
    substitution: "Para uma sopa mais encorpada, bata uma concha dos legumes no liquidificador e volte à panela.",
    proteinaPrincipal: "vegetariano",
    dish: { src: "/receitas/sopa-de-legumes-paprica-picante.jpg", alt: "Sopa de Legumes com Páprica Picante — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "camaroes-ao-alho-salsa-cebola-alho",
    title: "Camarões ao Alho com Salsa, Cebola e Alho",
    subtitle: "Camarões salteados na manteiga com alho dourado, servidos direto da frigideira.",
    intro: "Camarões salteados na manteiga com alho dourado, servidos direto da frigideira. O Salsa, Cebola e Alho reforça o aroma e dá o verde da finalização. Cinco minutos entre a panela e a mesa.",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "18 min",
    serves: "3 porções",
    difficulty: "Fácil",
    ingredients: ["500 g de camarão médio limpo, com cauda", "3 colheres (sopa) de manteiga", "1 colher (sopa) de azeite", "4 dentes de alho picados", "1 colher (sopa) de Salsa, Cebola e Alho Temperanzza", "Suco de 1/2 limão", "Sal a gosto"],
    steps: ["Tempere os camarões com sal e metade do Salsa, Cebola e Alho.", "Em uma frigideira de ferro, aqueça o azeite e 1 colher (sopa) de manteiga em fogo alto.", "Coloque os camarões e cozinhe por 2 minutos de cada lado, até ficarem rosados.", "Junte o restante da manteiga e o alho e cozinhe por 1 minuto.", "Finalize com o restante do Salsa, Cebola e Alho e o suco de limão. Sirva na frigideira."],
    chefWord: "Coloque o alho só no final: ele doura em segundos e amarga se passar do ponto.",
    whyItWorks: "Coloque o alho só no final: ele doura em segundos e amarga se passar do ponto.",
    substitution: "Sirva com arroz branco ou pão para aproveitar a manteiga temperada.",
    proteinaPrincipal: "pescados",
    dish: { src: "/receitas/camaroes-ao-alho-salsa-cebola-alho.jpg", alt: "Camarões ao Alho com Salsa, Cebola e Alho — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "peixe-assado-legumes-salsa-cebola-alho",
    title: "Peixe Assado com Legumes e Salsa, Cebola e Alho",
    subtitle: "Peixe com crosta de ervas assado sobre batatinhas, tomates-cereja, alho e alecrim.",
    intro: "Peixe com crosta de ervas assado sobre batatinhas, tomates-cereja, alho e alecrim. O Salsa, Cebola e Alho tempera o peixe e os legumes de uma só vez. Uma assadeira só, sem complicação.",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "55 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["800 g de filé de peixe firme (robalo, pescada ou salmão) em uma peça", "500 g de batatas bolinha cortadas ao meio", "15 tomates-cereja", "6 dentes de alho com casca", "3 ramos de alecrim", "4 colheres (sopa) de azeite", "2 colheres (sopa) de Salsa, Cebola e Alho Temperanzza", "Suco de 1 limão", "Sal a gosto"],
    steps: ["Preaqueça o forno a 200 °C.", "Misture as batatas e os dentes de alho com 2 colheres (sopa) de azeite, metade do Salsa, Cebola e Alho e sal. Espalhe em uma assadeira e asse por 20 minutos.", "Tempere o peixe com o suco de limão, sal e o restante do Salsa, Cebola e Alho, pressionando para formar uma crosta. Regue com o azeite restante.", "Retire a assadeira do forno, junte os tomates e o alecrim e coloque o peixe no centro.", "Asse por 15 a 18 minutos, até o peixe se soltar em lascas.", "Sirva na própria assadeira."],
    chefWord: "Pré-assar as batatas garante que elas fiquem macias no mesmo tempo que o peixe.",
    whyItWorks: "Pré-assar as batatas garante que elas fiquem macias no mesmo tempo que o peixe.",
    substitution: "Para conferir o ponto, pressione o peixe com um garfo: ele deve se separar em lascas.",
    proteinaPrincipal: "pescados",
    dish: { src: "/receitas/peixe-assado-legumes-salsa-cebola-alho.jpg", alt: "Peixe Assado com Legumes e Salsa, Cebola e Alho — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "peixe-grelhado-salada-salsa-cebola-alho",
    title: "Peixe Grelhado com Salada e Salsa, Cebola e Alho",
    subtitle: "Filé de peixe branco com marcas de grelha, servido com salada de folhas, tomate e cebola roxa.",
    intro: "Filé de peixe branco com marcas de grelha, servido com salada de folhas, tomate e cebola roxa. O Salsa, Cebola e Alho tempera o peixe e o molho da salada. Marca de grelha, azeite e tempero: o resto é o peixe.",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "almoco",
    profile: "ervas",
    category: "tradicional",
    time: "25 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["Para o peixe:", "2 filés de peixe branco (tilápia, pescada ou robalo), cerca de 400 g", "2 colheres (sopa) de azeite", "Suco de 1/2 limão", "2 colheres (chá) de Salsa, Cebola e Alho Temperanzza", "Sal a gosto", "Para a salada:", "2 xícaras de folhas (alface, rúcula e radicchio)", "8 tomates-cereja cortados ao meio", "1/4 de cebola roxa em fatias finas", "2 colheres (sopa) de azeite", "1 colher (sopa) de suco de limão"],
    steps: ["Seque bem os filés e tempere com o suco de limão, o azeite, sal e o Salsa, Cebola e Alho, reservando uma pitada para a salada.", "Aqueça bem uma grelha ou frigideira de ferro untada, em fogo alto.", "Grelhe os filés por 3 a 4 minutos de cada lado, sem mexer, até formar as marcas.", "Misture o azeite, o suco de limão, a pitada de tempero reservada e sal, e tempere as folhas, os tomates e a cebola.", "Sirva o peixe ao lado da salada."],
    chefWord: "Seque bem o filé antes de temperar: a umidade impede a formação das marcas de grelha.",
    whyItWorks: "Seque bem o filé antes de temperar: a umidade impede a formação das marcas de grelha.",
    substitution: "Use uma espátula larga para virar o peixe de uma só vez, sem quebrar.",
    proteinaPrincipal: "pescados",
    dish: { src: "/receitas/peixe-grelhado-salada-salsa-cebola-alho.jpg", alt: "Peixe Grelhado com Salada e Salsa, Cebola e Alho — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "arroz-ao-alho-salsa-cebola-alho",
    title: "Arroz ao Alho com Salsa, Cebola e Alho",
    subtitle: "Arroz branco soltinho, com alho dourado e o perfume verde das ervas.",
    intro: "Arroz branco soltinho, com alho dourado e o perfume verde das ervas. O Salsa, Cebola e Alho entra no refogado e na finalização. O básico perfeito, sem precisar picar nada além do alho.",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "almoco",
    profile: "ervas",
    category: "tradicional",
    time: "25 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["2 xícaras de arroz branco tipo 1", "4 xícaras de água fervente", "2 colheres (sopa) de óleo ou azeite", "3 dentes de alho picados", "1 colher (sopa) de Salsa, Cebola e Alho Temperanzza", "1 colher (chá) de sal"],
    steps: ["Lave o arroz até a água sair clara e escorra bem.", "Em uma panela, aqueça o óleo e doure o alho por 1 minuto, sem deixar queimar.", "Junte o arroz e metade do Salsa, Cebola e Alho e refogue por 2 minutos, até os grãos ficarem brilhantes.", "Adicione a água fervente e o sal, tampe e cozinhe em fogo baixo por 15 minutos, até secar.", "Desligue o fogo, deixe descansar tampado por 5 minutos, solte com um garfo e polvilhe o restante do tempero."],
    chefWord: "Água fervente na proporção de duas para uma é o que garante o arroz soltinho.",
    whyItWorks: "Água fervente na proporção de duas para uma é o que garante o arroz soltinho.",
    substitution: "Não mexa o arroz enquanto cozinha: isso libera amido e deixa os grãos grudados.",
    proteinaPrincipal: "vegetariano",
    dish: { src: "/receitas/arroz-ao-alho-salsa-cebola-alho.jpg", alt: "Arroz ao Alho com Salsa, Cebola e Alho — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "salmao-defumado-ervas-finas",
    title: "Salmão Defumado com Ervas Finas",
    subtitle: "Posta de salmão com pele crocante e uma crosta generosa de ervas por cima.",
    intro: "Posta de salmão com pele crocante e uma crosta generosa de ervas por cima. O Ervas Finas perfuma o peixe, e o fogo alto da frigideira traz o toque tostado e defumado. O mar encontra o jardim em um só prato.",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "22 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["2 postas de salmão com pele (cerca de 180 g cada)", "2 colheres (sopa) de azeite", "1 colher (sopa) de manteiga", "1 colher (sopa) de Ervas Finas Temperanzza", "Raspas de 1 limão", "Sal a gosto"],
    steps: ["Seque bem o salmão e tempere a pele com sal.", "Misture o Ervas Finas, as raspas de limão e 1 colher (sopa) de azeite até formar uma pasta. Espalhe sobre a parte de cima das postas.", "Aqueça o azeite restante em uma frigideira de ferro, em fogo alto. Coloque o salmão com a pele para baixo e pressione nos primeiros 30 segundos. Cozinhe por 5 a 6 minutos.", "Abaixe para fogo médio, junte a manteiga e, com uma colher, regue o salmão com a manteiga derretida por 3 a 4 minutos, até o centro ficar levemente rosado.", "Sirva com a crosta de ervas para cima."],
    chefWord: "Pressionar o salmão nos primeiros segundos impede que a pele encolha e garante crocância por igual.",
    whyItWorks: "Pressionar o salmão nos primeiros segundos impede que a pele encolha e garante crocância por igual.",
    substitution: "O ponto ideal é com o centro levemente rosado: ele termina de cozinhar no calor residual.",
    proteinaPrincipal: "pescados",
    dish: { src: "/receitas/salmao-defumado-ervas-finas.jpg", alt: "Salmão Defumado com Ervas Finas — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "torrada-carnivora-ervas-finas",
    title: "Torrada Carnívora com Ervas Finas",
    subtitle: "Fatias de pão carnívoro douradas na frigideira, com manteiga de ervas escorrendo.",
    intro: "Fatias de pão carnívoro douradas na frigideira, com manteiga de ervas escorrendo. O Ervas Finas perfuma a manteiga e dá o acabamento verde. Crocância absoluta para o café da manhã, caldos e antepastos.",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "cafe",
    profile: "ervas",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["Para o pão carnívoro:", "300 g de peito de frango cozido e desfiado", "4 ovos", "150 g de queijo muçarela ralado", "1 colher (chá) de fermento químico em pó", "Sal a gosto", "Para a manteiga de ervas:", "3 colheres (sopa) de manteiga em temperatura ambiente", "1 colher (sopa) de Ervas Finas Temperanzza", "1 dente de alho ralado"],
    steps: ["Preaqueça o forno a 180 °C e unte uma fôrma de bolo inglês.", "Processe o frango, os ovos, a muçarela, o fermento e o sal até formar uma massa homogênea. Coloque na fôrma e asse por 30 minutos. Deixe esfriar completamente.", "Corte o pão em fatias de 1,5 cm.", "Misture a manteiga, o Ervas Finas e o alho.", "Passe a manteiga de ervas nas fatias e doure em uma frigideira, em fogo médio, por 2 minutos de cada lado.", "Sirva quente."],
    chefWord: "Espere o pão esfriar completamente antes de fatiar: morno, ele esfarela.",
    whyItWorks: "Espere o pão esfriar completamente antes de fatiar: morno, ele esfarela.",
    substitution: "As fatias podem ser congeladas e tostadas direto do freezer.",
    proteinaPrincipal: "paes",
    dish: { src: "/receitas/torrada-carnivora-ervas-finas.jpg", alt: "Torrada Carnívora com Ervas Finas — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bolo-carnivoro-salgado-chimi-churri-sem-pimenta",
    title: "Bolo Carnívoro Salgado com Chimi Churri Sem Pimenta",
    subtitle: "Bolo salgado de textura macia e casca dourada, feito sem farinha e sem carboidratos.",
    intro: "Bolo salgado de textura macia e casca dourada, feito sem farinha e sem carboidratos. O Chimi Churri Sem Pimenta dá o aroma de ervas e alho à massa, sem ardência. Ótimo para o café da manhã ou para levar na marmita.",
    featuredHandle: "chimichurri-sem-pimenta",
    compatibleDiets: [],
    moment: "cafe",
    profile: "ervas",
    category: "tradicional",
    time: "55 min",
    serves: "8 fatias",
    difficulty: "Fácil",
    ingredients: ["400 g de peito de frango cozido e desfiado", "5 ovos", "150 g de queijo muçarela ralado", "50 g de queijo parmesão ralado", "3 colheres (sopa) de manteiga derretida", "1 colher (sopa) de fermento químico em pó", "1 colher (sopa) de Chimi Churri Sem Pimenta Temperanzza", "Sal a gosto"],
    steps: ["Preaqueça o forno a 180 °C. Unte e forre com papel-manteiga uma fôrma de bolo inglês.", "Processe o frango, os ovos e a manteiga derretida até formar uma massa lisa.", "Junte os queijos, o Chimi Churri Sem Pimenta e o sal e pulse até incorporar.", "Acrescente o fermento e misture delicadamente com uma espátula.", "Coloque na fôrma e asse por 40 minutos, até dourar e um palito sair seco.", "Desenforme ainda morno e fatie."],
    chefWord: "Antes de assar, pincele a superfície com manteiga e polvilhe um pouco de Chimi Churri Sem Pimenta para uma casca mais aromática.",
    whyItWorks: "Antes de assar, pincele a superfície com manteiga e polvilhe um pouco de Chimi Churri Sem Pimenta para uma casca mais aromática.",
    substitution: "Fatias tostadas na frigideira com manteiga viram um lanche rápido.",
    proteinaPrincipal: "paes",
    dish: { src: "/receitas/bolo-carnivoro-salgado-chimi-churri-sem-pimenta.jpg", alt: "Bolo Carnívoro Salgado com Chimi Churri Sem Pimenta — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "abacate-recheado-frango-chimi-churri-sem-pimenta",
    title: "Abacate Recheado com Frango e Chimi Churri Sem Pimenta",
    subtitle: "Metades de abacate recheadas com frango desfiado cremoso e bem temperado.",
    intro: "Metades de abacate recheadas com frango desfiado cremoso e bem temperado. O Chimi Churri Sem Pimenta traz o sabor das ervas sem ardência. O lanche frio que sustenta o dia todo.",
    featuredHandle: "chimichurri-sem-pimenta",
    compatibleDiets: [],
    moment: "lanche",
    profile: "ervas",
    category: "tradicional",
    time: "35 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["1 abacate maduro (ou 2 avocados)", "250 g de peito de frango", "2 colheres (sopa) de maionese ou iogurte natural", "1 colher (sopa) de azeite", "Suco de 1/2 limão", "2 colheres (chá) de Chimi Churri Sem Pimenta Temperanzza", "Sal a gosto"],
    steps: ["Cozinhe o frango em água com sal por 20 minutos. Deixe esfriar e desfie.", "Misture o frango com a maionese, o azeite, o Chimi Churri Sem Pimenta e sal.", "Corte o abacate ao meio, retire o caroço e regue com o suco de limão.", "Recheie as metades com o frango e polvilhe mais uma pitada de Chimi Churri Sem Pimenta.", "Sirva frio."],
    chefWord: "Regar o abacate com limão evita que ele escureça.",
    whyItWorks: "Regar o abacate com limão evita que ele escureça.",
    substitution: "Se o abacate for grande, sirva meia fruta por pessoa com uma salada verde ao lado.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/abacate-recheado-frango-chimi-churri-sem-pimenta.jpg", alt: "Abacate Recheado com Frango e Chimi Churri Sem Pimenta — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "figado-acebolado-edu-guedes",
    title: "Fígado Acebolado com Edu Guedes",
    subtitle: "Bifes de fígado macios, selados na frigideira de ferro e cobertos com cebolas douradas.",
    intro: "Bifes de fígado macios, selados na frigideira de ferro e cobertos com cebolas douradas. O Edu Guedes tempera a carne e acompanha a cebola. A densidade nutritiva com o aroma que a torna irresistível.",
    featuredHandle: "tempero-do-edu",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "30 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["600 g de fígado bovino em bifes", "Suco de 1 limão", "2 cebolas grandes em rodelas", "2 colheres (sopa) de manteiga", "1 colher (sopa) de azeite", "1 colher (sopa) de Edu Guedes Temperanzza", "Sal a gosto"],
    steps: ["Retire a película do fígado e deixe os bifes de molho em água com o suco de limão por 10 minutos. Escorra e seque bem.", "Tempere os bifes com o Edu Guedes e sal.", "Aqueça o azeite em uma frigideira de ferro em fogo alto e sele os bifes por 2 minutos de cada lado. Reserve.", "Na mesma frigideira, derreta a manteiga e doure as cebolas em fogo médio por 8 a 10 minutos, com uma pitada de Edu Guedes.", "Volte o fígado à frigideira por 1 minuto e sirva com as cebolas por cima."],
    chefWord: "O fígado passa do ponto rápido: cozinhe só até perder o tom rosado para mantê-lo macio.",
    whyItWorks: "O fígado passa do ponto rápido: cozinhe só até perder o tom rosado para mantê-lo macio.",
    substitution: "Deixar de molho no limão suaviza o sabor forte do fígado.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/figado-acebolado-edu-guedes.jpg", alt: "Fígado Acebolado com Edu Guedes — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ovos-ao-molho-queijo-gratinado-edu-guedes",
    title: "Ovos ao Molho com Queijo Gratinado e Edu Guedes",
    subtitle: "Ovos cozidos cortados ao meio, cobertos com molho de tomate caseiro e queijo gratinado.",
    intro: "Ovos cozidos cortados ao meio, cobertos com molho de tomate caseiro e queijo gratinado. O Edu Guedes tempera o molho e finaliza o prato. Simples, proteico e cheio de sabor.",
    featuredHandle: "tempero-do-edu",
    compatibleDiets: [],
    moment: "cafe",
    profile: "casa",
    category: "tradicional",
    time: "35 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["8 ovos", "2 xícaras de molho de tomate caseiro (ou passata)", "1 cebola pequena picada", "2 dentes de alho picados", "1 colher (sopa) de azeite", "100 g de queijo muçarela ralado", "2 colheres (sopa) de queijo parmesão ralado", "2 colheres (chá) de Edu Guedes Temperanzza", "Sal a gosto", "Cheiro-verde picado para finalizar"],
    steps: ["Cozinhe os ovos em água fervente por 10 minutos. Passe para uma tigela com água e gelo, descasque e corte ao meio.", "Refogue a cebola e o alho no azeite. Junte o molho de tomate e metade do Edu Guedes e cozinhe por 10 minutos. Acerte o sal.", "Preaqueça o forno a 220 °C.", "Em um refratário, espalhe parte do molho, distribua os ovos com a gema para cima e cubra com o restante do molho.", "Cubra com os queijos e o restante do Edu Guedes e leve ao forno por 10 minutos, até gratinar.", "Finalize com cheiro-verde."],
    chefWord: "O banho de gelo interrompe o cozimento e facilita descascar os ovos.",
    whyItWorks: "O banho de gelo interrompe o cozimento e facilita descascar os ovos.",
    substitution: "Sirva com torradas carnívoras ou pão para aproveitar o molho.",
    proteinaPrincipal: "ovo",
    dish: { src: "/receitas/ovos-ao-molho-queijo-gratinado-edu-guedes.jpg", alt: "Ovos ao Molho com Queijo Gratinado e Edu Guedes — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bife-na-manteiga-na-frigideira-chimi-churri-picante",
    title: "Bife na Manteiga na Frigideira com Chimi Churri Picante",
    subtitle: "Bife alto selado na frigideira de ferro, com marcas de grelha e manteiga derretendo por cima.",
    intro: "Bife alto selado na frigideira de ferro, com marcas de grelha e manteiga derretendo por cima. O Chimi Churri Picante entra na manteiga e desperta o sabor da carne. A manteiga derrete, o chimichurri acorda e o bife fica pronto.",
    featuredHandle: "chimichurri-picante",
    compatibleDiets: [],
    moment: "jantar",
    profile: "citrico-picante",
    category: "tradicional",
    time: "20 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["2 bifes de contrafilé ou ancho com 3 cm de altura (cerca de 350 g cada)", "1 colher (sopa) de azeite", "3 colheres (sopa) de manteiga em temperatura ambiente", "2 colheres (chá) de Chimi Churri Picante Temperanzza", "Sal grosso moído a gosto"],
    steps: ["Retire os bifes da geladeira 30 minutos antes. Seque bem e tempere com sal.", "Misture a manteiga com o Chimi Churri Picante e leve à geladeira enquanto prepara a carne.", "Aqueça muito bem uma frigideira de ferro com o azeite e sele os bifes por 3 a 4 minutos de cada lado, para ponto entre malpassado e ao ponto.", "Deixe os bifes descansarem por 5 minutos e coloque uma colherada da manteiga de Chimi Churri sobre cada um.", "Sirva enquanto a manteiga derrete."],
    chefWord: "Deixar a carne descansar depois de selada mantém os sucos dentro do bife.",
    whyItWorks: "Deixar a carne descansar depois de selada mantém os sucos dentro do bife.",
    substitution: "A manteiga de Chimi Churri pode ser feita em maior quantidade e guardada no freezer por até 3 meses.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/bife-na-manteiga-na-frigideira-chimi-churri-picante.jpg", alt: "Bife na Manteiga na Frigideira com Chimi Churri Picante — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "brunch-na-frigideira-chimi-churri-picante",
    title: "Brunch na Frigideira com Chimi Churri Picante",
    subtitle: "Legumes salteados, queijo gratinado e ovos assados direto na frigideira de ferro, com a gema mole no ponto.",
    intro: "Legumes salteados, queijo gratinado e ovos assados direto na frigideira de ferro, com a gema mole no ponto. O Chimi Churri Picante dá frescor e um calor leve ao conjunto. Um brunch completo, servido na própria panela.",
    featuredHandle: "chimichurri-picante",
    compatibleDiets: [],
    moment: "cafe",
    profile: "citrico-picante",
    category: "tradicional",
    time: "35 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["2 colheres (sopa) de azeite", "1 cebola roxa em pétalas", "1 pimentão vermelho em cubos", "1 xícara de floretes de brócolis", "10 tomates-cereja", "4 ovos", "80 g de queijo muçarela ralado", "2 colheres (chá) de Chimi Churri Picante Temperanzza", "Sal a gosto"],
    steps: ["Preaqueça o forno a 200 °C.", "Em uma frigideira de ferro, aqueça o azeite e salteie a cebola, o pimentão e o brócolis por 6 minutos.", "Junte os tomates, metade do Chimi Churri Picante e sal. Cozinhe por mais 2 minutos.", "Abra 4 espaços entre os legumes, quebre um ovo em cada um e espalhe o queijo ao redor.", "Leve ao forno por 8 a 10 minutos, até as claras firmarem e as gemas continuarem moles.", "Finalize com o restante do Chimi Churri Picante e sirva na frigideira."],
    chefWord: "Tire do forno quando as claras firmarem: a gema continua cozinhando no calor da frigideira.",
    whyItWorks: "Tire do forno quando as claras firmarem: a gema continua cozinhando no calor da frigideira.",
    substitution: "Aproveite os legumes da geladeira: abobrinha, cogumelos e espinafre também funcionam.",
    proteinaPrincipal: "ovo",
    dish: { src: "/receitas/brunch-na-frigideira-chimi-churri-picante.jpg", alt: "Brunch na Frigideira com Chimi Churri Picante — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "lombo-grelhado-chimi-churri-picante",
    title: "Lombo Grelhado com Chimi Churri Picante",
    subtitle: "Lombo suíno marinado, dourado na frigideira e servido em fatias suculentas.",
    intro: "Lombo suíno marinado, dourado na frigideira e servido em fatias suculentas. O Chimi Churri Picante tempera a carne com ervas, alho e um calor na medida. Um corte magro que ganha alma argentina.",
    featuredHandle: "chimichurri-picante",
    compatibleDiets: [],
    moment: "jantar",
    profile: "citrico-picante",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["800 g de lombo suíno em peça", "3 colheres (sopa) de azeite", "Suco de 1 limão", "2 dentes de alho amassados", "2 colheres (sopa) de Chimi Churri Picante Temperanzza", "Sal a gosto"],
    steps: ["Misture o azeite, o suco de limão, o alho, o Chimi Churri Picante e sal. Passe em todo o lombo e deixe marinar por 1 hora na geladeira.", "Retire da geladeira 20 minutos antes e preaqueça o forno a 180 °C.", "Em uma frigideira de ferro, em fogo médio-alto, doure o lombo de todos os lados por cerca de 8 minutos.", "Leve a frigideira ao forno por 20 minutos, até o centro atingir 63 °C.", "Deixe descansar por 8 minutos e corte em fatias."],
    chefWord: "Um termômetro de cozinha ajuda: 63 °C no centro é o ponto de lombo suculento e seguro.",
    whyItWorks: "Um termômetro de cozinha ajuda: 63 °C no centro é o ponto de lombo suculento e seguro.",
    substitution: "Fatie contra as fibras para cada pedaço ficar mais macio.",
    proteinaPrincipal: "suino",
    dish: { src: "/receitas/lombo-grelhado-chimi-churri-picante.jpg", alt: "Lombo Grelhado com Chimi Churri Picante — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bife-acebolado-lemon-pepper",
    title: "Bife Acebolado com Lemon Pepper",
    subtitle: "Bife suculento, rosado por dentro, coberto com anéis de cebola dourada.",
    intro: "Bife suculento, rosado por dentro, coberto com anéis de cebola dourada. O Lemon Pepper traz o toque cítrico e picante que equilibra a doçura da cebola. Um clássico brasileiro com sabor novo.",
    featuredHandle: "lemon-pepper",
    compatibleDiets: [],
    moment: "almoco",
    profile: "citrico-picante",
    category: "tradicional",
    time: "25 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["2 bifes de contrafilé com 2 cm de altura (cerca de 300 g cada)", "2 cebolas em anéis", "2 colheres (sopa) de manteiga", "1 colher (sopa) de azeite", "2 colheres (chá) de Lemon Pepper Temperanzza", "Sal a gosto"],
    steps: ["Tempere os bifes com o Lemon Pepper e sal.", "Aqueça muito bem uma frigideira com o azeite e sele os bifes por 3 minutos de cada lado. Reserve para descansar.", "Na mesma frigideira, derreta a manteiga e doure as cebolas em fogo médio por 8 minutos, até ficarem macias e douradas. Tempere com uma pitada de Lemon Pepper.", "Coloque o bife no prato e cubra com as cebolas."],
    chefWord: "Anéis de cebola da mesma espessura douram por igual.",
    whyItWorks: "Anéis de cebola da mesma espessura douram por igual.",
    substitution: "Use a mesma frigideira da carne para a cebola: o fundo caramelizado dá mais sabor.",
    proteinaPrincipal: "bovina",
    dish: { src: "/receitas/bife-acebolado-lemon-pepper.jpg", alt: "Bife Acebolado com Lemon Pepper — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ensopado-de-frango-quiabo-paprica-doce",
    title: "Ensopado de Frango com Quiabo e Páprica Doce",
    subtitle: "Sobrecoxas douradas cozidas com quiabo em panela de ferro, em um molho encorpado.",
    intro: "Sobrecoxas douradas cozidas com quiabo em panela de ferro, em um molho encorpado. A Páprica Doce dá cor e sabor sem ardência. O clássico mineiro, do jeito da casa.",
    featuredHandle: "paprica-doce",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "55 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1 kg de sobrecoxas de frango", "400 g de quiabo em pedaços de 3 cm", "1 cebola picada", "3 dentes de alho picados", "2 tomates picados", "2 colheres (sopa) de óleo", "1 colher (sopa) de Páprica Doce Temperanzza", "Suco de 1/2 limão", "400 ml de água quente", "Sal a gosto", "Cheiro-verde picado para finalizar"],
    steps: ["Tempere o frango com a Páprica Doce e sal.", "Em uma frigideira, aqueça 1 colher (sopa) de óleo e refogue o quiabo com o suco de limão em fogo alto por 5 minutos, até perder a baba. Reserve.", "Em uma panela, aqueça o restante do óleo e doure o frango. Junte a cebola, o alho e o tomate e refogue até o tomate desmanchar.", "Adicione a água quente, tampe e cozinhe em fogo baixo por 25 minutos.", "Junte o quiabo, cozinhe por mais 5 a 8 minutos, acerte o sal e finalize com cheiro-verde."],
    chefWord: "Refogar o quiabo à parte com limão elimina a baba.",
    whyItWorks: "Refogar o quiabo à parte com limão elimina a baba.",
    substitution: "Sirva com angu e arroz branco.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/ensopado-de-frango-quiabo-paprica-doce.jpg", alt: "Ensopado de Frango com Quiabo e Páprica Doce — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-a-passarinho-paprica-doce",
    title: "Frango à Passarinho com Páprica Doce",
    subtitle: "Pedaços de frango bem dourados na frigideira de ferro, com pele crocante e carne suculenta.",
    intro: "Pedaços de frango bem dourados na frigideira de ferro, com pele crocante e carne suculenta. A Páprica Doce dá a cor do apetite sem o ardor da pimenta. Finalizado com sal grosso, como pede um bom petisco de boteco.",
    featuredHandle: "paprica-doce",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1 kg de frango cortado à passarinho (ou sobrecoxas)", "Suco de 1 limão", "4 dentes de alho amassados", "1 colher (sopa) de Páprica Doce Temperanzza", "3 colheres (sopa) de óleo", "Sal a gosto", "Sal grosso para finalizar"],
    steps: ["Tempere o frango com o suco de limão, o alho, a Páprica Doce e sal. Deixe marinar por 30 minutos.", "Seque levemente os pedaços com papel-toalha.", "Aqueça o óleo em uma frigideira de ferro em fogo médio-alto e coloque o frango com a pele para baixo, sem amontoar. Cozinhe por 10 a 12 minutos, até a pele ficar crocante.", "Vire os pedaços, abaixe o fogo e cozinhe com a frigideira semitampada por 12 a 15 minutos, até cozinhar por dentro.", "Destampe, aumente o fogo por 2 minutos e finalize com sal grosso."],
    chefWord: "Comece com a pele para baixo e não mexa: é assim que ela fica crocante.",
    whyItWorks: "Comece com a pele para baixo e não mexa: é assim que ela fica crocante.",
    substitution: "Para uma versão ainda mais sequinha, termine no forno a 220 °C por 10 minutos.",
    proteinaPrincipal: "frango",
    dish: { src: "/receitas/frango-a-passarinho-paprica-doce.jpg", alt: "Frango à Passarinho com Páprica Doce — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "couve-flor-gratinada-curcuma",
    title: "Couve-Flor Gratinada com Cúrcuma",
    subtitle: "Floretes de couve-flor cobertos com molho cremoso dourado e queijo gratinado.",
    intro: "Floretes de couve-flor cobertos com molho cremoso dourado e queijo gratinado. A Cúrcuma dá a cor de ouro e um sabor suave e terroso. Visual de ouro, sabor de terra.",
    featuredHandle: "curcuma",
    compatibleDiets: [],
    moment: "jantar",
    profile: "puras",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1 couve-flor média em floretes", "2 colheres (sopa) de manteiga", "1 colher (sopa) de amido de milho", "400 ml de leite", "100 g de queijo muçarela ralado", "50 g de queijo parmesão ralado", "1 colher (chá) de Cúrcuma Temperanzza", "1 pitada de noz-moscada", "Sal a gosto"],
    steps: ["Cozinhe os floretes em água fervente com sal por 5 minutos. Escorra muito bem.", "Em uma panela, derreta a manteiga, junte o amido de milho e mexa. Acrescente o leite e a Cúrcuma e mexa até engrossar.", "Tempere o molho com sal e noz-moscada e junte metade da muçarela.", "Coloque a couve-flor em um refratário, cubra com o molho e depois com o restante da muçarela e o parmesão.", "Asse a 200 °C por 20 a 25 minutos, até dourar."],
    chefWord: "Escorra muito bem a couve-flor: a água que sobra deixa o gratinado aguado.",
    whyItWorks: "Escorra muito bem a couve-flor: a água que sobra deixa o gratinado aguado.",
    substitution: "Uma pitada de pimenta-do-reino ajuda o corpo a aproveitar melhor a cúrcuma.",
    proteinaPrincipal: "vegetariano",
    dish: { src: "/receitas/couve-flor-gratinada-curcuma.jpg", alt: "Couve-Flor Gratinada com Cúrcuma — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "panela-de-legumes-assados-curcuma",
    title: "Panela de Legumes Assados com Cúrcuma",
    subtitle: "Abóbora, abobrinha, pimentão e cebola roxa assados até caramelizar nas bordas.",
    intro: "Abóbora, abobrinha, pimentão e cebola roxa assados até caramelizar nas bordas. A Cúrcuma pinta os legumes de dourado e realça o sabor natural de cada um. Uma explosão de cores, servida na própria panela.",
    featuredHandle: "curcuma",
    compatibleDiets: [],
    moment: "jantar",
    profile: "puras",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["400 g de abóbora cabotiá em gomos, com casca", "1 abobrinha em rodelas grossas", "1 pimentão vermelho em tiras largas", "1 cebola roxa em gomos", "4 colheres (sopa) de azeite", "2 colheres (chá) de Cúrcuma Temperanzza", "1/2 colher (chá) de pimenta-do-reino", "Sal a gosto", "Ramos de tomilho"],
    steps: ["Preaqueça o forno a 220 °C.", "Misture o azeite, a Cúrcuma, a pimenta-do-reino e o sal.", "Envolva a abóbora na mistura, espalhe em uma panela de ferro ou assadeira e asse por 15 minutos.", "Envolva os demais legumes no restante da mistura, junte à abóbora e asse por mais 20 minutos, virando na metade do tempo.", "Finalize com o tomilho e sirva."],
    chefWord: "Não amontoe os legumes: espalhados, eles assam e caramelizam em vez de cozinhar no vapor.",
    whyItWorks: "Não amontoe os legumes: espalhados, eles assam e caramelizam em vez de cozinhar no vapor.",
    substitution: "Sirva como acompanhamento de carnes ou com um ovo pochê por cima para uma refeição completa.",
    proteinaPrincipal: "vegetariano",
    dish: { src: "/receitas/panela-de-legumes-assados-curcuma.jpg", alt: "Panela de Legumes Assados com Cúrcuma — Temperanzza" },
    hero: { color: "oklch(0.52 0.21 28)" },
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return RECIPES.find((recipe) => recipe.slug === slug);
}

export function getRecipesByHandle(handle: string): Recipe[] {
  return RECIPES.filter((recipe) => recipe.featuredHandle === handle);
}

export type Protein = "frango" | "bovina" | "suino" | "pescados" | "ovo" | "paes" | "vegetariano";

export const PROTEINS: Record<Protein, string> = {
  frango: "Frango",
  bovina: "Carne bovina",
  suino: "Suíno",
  pescados: "Peixe & Frutos do Mar",
  ovo: "Ovo",
  paes: "Pães",
  vegetariano: "Vegetariano",
};

export const PROTEIN_ORDER: Protein[] = ["frango", "bovina", "suino", "pescados", "ovo", "paes", "vegetariano"];
export const RECIPE_PROTEIN: Record<string, Protein> = Object.fromEntries(RECIPES.map((recipe) => [recipe.slug, recipe.proteinaPrincipal ?? "vegetariano"]));
export function getRecipeProtein(recipe: Recipe): Protein | undefined {
  return recipe.proteinaPrincipal ?? RECIPE_PROTEIN[recipe.slug];
}
