/** Biblioteca gastronômica sincronizada com database/seed-data.json. */
import type { DietKey } from "./diets";
import type { ProductDiet } from "./dietCompatibility";

export type Moment = "cafe" | "almoco" | "jantar" | "lanche";
export type RecipeCategory = "tradicional";

export interface Recipe {
  slug: string;
  title: string;
  featuredHandle: string;
  compatibleDiets: DietKey[];
  moment: Moment;
  profile: ProductDiet["profile"];
  category?: RecipeCategory;
  intro: string;
  ingredients: string[];
  steps: string[];
  whyItWorks: string;
  substitution: string;
  hero: { color: string };
  subtitle?: string;
  chefWord?: string;
  time?: string;
  serves?: string;
  difficulty?: "Fácil" | "Médio" | "Avançado";
  harmonization?: string[];
  proteinaPrincipal?: Protein;
  dish?: { src: string; alt: string };
  relatedSlugs?: string[];
}

export const MOMENTS: Record<Moment, string> = {
  cafe: "Café da manhã",
  almoco: "Almoço",
  jantar: "Jantar",
  lanche: "Lanche",
};

export const CATEGORIES: Record<RecipeCategory, { label: string; short: string }> = {
  tradicional: { label: "Mesa de Todos — Tradicional", short: "Tradicional" },
};

export const RECIPES: Recipe[] = [
  {
    slug: "bolo-de-milho-com-temperaflix-bacon",
    title: "Bolo de Milho com Temperaflix Bacon",
    subtitle: "Bolo cremoso de milho verde com toque de bacon defumado",
    intro: "Bolo cremoso de milho verde com toque de bacon defumado",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "cafe",
    profile: "defumado",
    category: "tradicional",
    time: "45 min",
    serves: "8 porções",
    difficulty: "Fácil",
    ingredients: ["2 xícaras de milho verde", "1 xícara de farinha", "3 ovos", "1 xícara de leite", "100g Temperaflix Bacon"],
    steps: ["Bata o milho com os ovos e leite.", "Adicione a farinha e Temperaflix Bacon.", "Asse por 40 min a 180°C."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Bacon.",
    whyItWorks: "Bolo cremoso de milho verde com toque de bacon defumado",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "pao-frances-temperado-com-tempero-mineiro",
    title: "Pão Francês Temperado com Tempero Mineiro",
    subtitle: "Pão francês crocante com tempero mineiro na massa",
    intro: "Pão francês crocante com tempero mineiro na massa",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "cafe",
    profile: "casa",
    category: "tradicional",
    time: "120 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["500g farinha de trigo", "250ml água", "10g sal", "7g fermento", "50g Tempero Mineiro"],
    steps: ["Misture ingredientes, sove por 10 min, deixe fermentar 1h.", "Modele e asse a 220°C por 20 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Tempero Mineiro.",
    whyItWorks: "Pão francês crocante com tempero mineiro na massa",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bolo-de-cenoura-com-ervas-finas",
    title: "Bolo de Cenoura com Ervas Finas",
    subtitle: "Bolo úmido de cenoura com cobertura de ervas",
    intro: "Bolo úmido de cenoura com cobertura de ervas",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "cafe",
    profile: "ervas",
    category: "tradicional",
    time: "50 min",
    serves: "10 porções",
    difficulty: "Médio",
    ingredients: ["3 cenouras grandes", "3 ovos", "1 xícara óleo", "2 xícaras farinha", "100g Ervas Finas"],
    steps: ["Bata cenoura com ovos e óleo.", "Misture farinha e fermento.", "Adicione Ervas Finas.", "Asse a 180°C por 45 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Ervas Finas.",
    whyItWorks: "Bolo úmido de cenoura com cobertura de ervas",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "quiche-de-queijo-com-curcuma",
    title: "Quiche de Queijo com Cúrcuma",
    subtitle: "Quiche cremosa com cúrcuma anti-inflamatória",
    intro: "Quiche cremosa com cúrcuma anti-inflamatória",
    featuredHandle: "curcuma",
    compatibleDiets: [],
    moment: "cafe",
    profile: "puras",
    category: "tradicional",
    time: "55 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["1 massa de pastel", "200g queijo meia cura", "4 ovos", "200ml creme", "30g Cúrcuma"],
    steps: ["Coloque massa na forma.", "Misture ovos, creme, queijo e Cúrcuma.", "Despeje e asse a 200°C por 40 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Cúrcuma.",
    whyItWorks: "Quiche cremosa com cúrcuma anti-inflamatória",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "ovo",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bolo-de-maca-com-lemon-pepper",
    title: "Bolo de Maçã com Lemon Pepper",
    subtitle: "Bolo fofinho de maçã com toque cítrico",
    intro: "Bolo fofinho de maçã com toque cítrico",
    featuredHandle: "lemon-pepper",
    compatibleDiets: [],
    moment: "cafe",
    profile: "citrico-picante",
    category: "tradicional",
    time: "50 min",
    serves: "8 porções",
    difficulty: "Médio",
    ingredients: ["4 maçãs médias", "2 ovos", "200ml óleo", "2 xícaras farinha", "50g Lemon Pepper"],
    steps: ["Ralhe maçãs, misture com ovos e óleo.", "Adicione farinha e Lemon Pepper.", "Asse a 180°C por 45 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Lemon Pepper.",
    whyItWorks: "Bolo fofinho de maçã com toque cítrico",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "pao-de-queijo-com-salsa-cebola-e-alho",
    title: "Pão de Queijo com Salsa Cebola e Alho",
    subtitle: "Pão de queijo tradicional mineiro temperado",
    intro: "Pão de queijo tradicional mineiro temperado",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "cafe",
    profile: "ervas",
    category: "tradicional",
    time: "30 min",
    serves: "12 porções",
    difficulty: "Fácil",
    ingredients: ["500g polvilho", "200g queijo meia cura", "100ml leite", "50g Salsa Cebola e Alho"],
    steps: ["Aqueça leite e óleo.", "Misture polvilho e queijo.", "Adicione Salsa Cebola e Alho.", "Asse a 200°C por 25 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Salsa Cebola e Alho.",
    whyItWorks: "Pão de queijo tradicional mineiro temperado",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "arroz-com-brocolis-e-ana-maria",
    title: "Arroz com Brócolis e Ana Maria",
    subtitle: "Arroz integral com brócolis e tempero mineiro clássico",
    intro: "Arroz integral com brócolis e tempero mineiro clássico",
    featuredHandle: "ana-maria",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "35 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["2 xícaras arroz integral", "4 xícaras água", "2 buquês brócolis", "50ml azeite", "40g Ana Maria"],
    steps: ["Cozinhe arroz na água com azeite.", "Cozinhe brócolis separado.", "Misture tudo com Ana Maria e refogue."],
    chefWord: "Um preparo pensado para destacar o sabor de Ana Maria.",
    whyItWorks: "Arroz integral com brócolis e tempero mineiro clássico",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-assado-com-paprica-defumada",
    title: "Frango Assado com Páprica Defumada",
    subtitle: "Frango crocante com páprica defumada da Hungria",
    intro: "Frango crocante com páprica defumada da Hungria",
    featuredHandle: "paprica-defumada",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "60 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["1 frango inteiro", "50g Páprica Defumada", "4 colheres azeite", "Sal e limão"],
    steps: ["Tempere frango com Páprica Defumada, azeite, sal e limão.", "Asse a 200°C por 55 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Páprica Defumada.",
    whyItWorks: "Frango crocante com páprica defumada da Hungria",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "frango",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "carne-com-chimi-churri-picante",
    title: "Carne com Chimi Churri Picante",
    subtitle: "Carne grelhada com chimichurri argentino defumado",
    intro: "Carne grelhada com chimichurri argentino defumado",
    featuredHandle: "chimichurri-picante",
    compatibleDiets: [],
    moment: "almoco",
    profile: "citrico-picante",
    category: "tradicional",
    time: "40 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["800g contrafilé", "60g Chimi Churri Picante", "100ml azeite"],
    steps: ["Grelhe carne em fogo alto.", "Faça molho: Chimi Churri Picante + azeite.", "Sirva sobre a carne."],
    chefWord: "Um preparo pensado para destacar o sabor de Chimi Churri Picante.",
    whyItWorks: "Carne grelhada com chimichurri argentino defumado",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "peixe-ao-limao-com-lemon-pepper",
    title: "Peixe ao Limão com Lemon Pepper",
    subtitle: "Peixe delicado com toque de pimenta preta e limão",
    intro: "Peixe delicado com toque de pimenta preta e limão",
    featuredHandle: "lemon-pepper",
    compatibleDiets: [],
    moment: "almoco",
    profile: "citrico-picante",
    category: "tradicional",
    time: "30 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["800g filé de peixe branco", "2 limões", "50g Lemon Pepper", "30ml azeite"],
    steps: ["Coloque peixe em assadeira.", "Cubra com Lemon Pepper, suco de limão e azeite.", "Asse a 190°C por 25 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Lemon Pepper.",
    whyItWorks: "Peixe delicado com toque de pimenta preta e limão",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "pescados",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "legumes-assados-com-ervas-finas",
    title: "Legumes Assados com Ervas Finas",
    subtitle: "Mix de legumes coloridos temperado com ervas premium",
    intro: "Mix de legumes coloridos temperado com ervas premium",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "almoco",
    profile: "ervas",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["200g abóbora", "200g cenoura", "200g abobrinha", "100g cebola", "60g Ervas Finas", "80ml azeite"],
    steps: ["Corte legumes em cubos.", "Misture com azeite e Ervas Finas.", "Asse a 200°C por 40 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Ervas Finas.",
    whyItWorks: "Mix de legumes coloridos temperado com ervas premium",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "risoto-cremoso-com-curcuma",
    title: "Risoto Cremoso com Cúrcuma",
    subtitle: "Risoto tradicional italiano com propriedades da cúrcuma",
    intro: "Risoto tradicional italiano com propriedades da cúrcuma",
    featuredHandle: "curcuma",
    compatibleDiets: [],
    moment: "almoco",
    profile: "puras",
    category: "tradicional",
    time: "35 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["2 xícaras arroz arbório", "800ml caldo quente", "100ml vinho branco", "1 cebola", "100g queijo", "40g Cúrcuma"],
    steps: ["Refogue cebola.", "Adicione arroz.", "Vá adicionando caldo quente aos poucos.", "Finalize com queijo e Cúrcuma."],
    chefWord: "Um preparo pensado para destacar o sabor de Cúrcuma.",
    whyItWorks: "Risoto tradicional italiano com propriedades da cúrcuma",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "linguine-ao-molho-branco-com-edu-guedes",
    title: "Linguine ao Molho Branco com Edu Guedes",
    subtitle: "Massa fresca com molho cremoso e tempero versátil",
    intro: "Massa fresca com molho cremoso e tempero versátil",
    featuredHandle: "tempero-do-edu",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "25 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["400g linguine", "200ml creme de leite", "100g mantega", "50g queijo parmesão", "50g Edu Guedes"],
    steps: ["Cozinhe linguine.", "Faça molho: derreta manteiga, adicione creme e Edu Guedes.", "Misture com massa."],
    chefWord: "Um preparo pensado para destacar o sabor de Edu Guedes.",
    whyItWorks: "Massa fresca com molho cremoso e tempero versátil",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "costela-assada-com-temperaflix-tradicional",
    title: "Costela Assada com Temperaflix Tradicional",
    subtitle: "Costela morna com tempero gourmet mineiro",
    intro: "Costela morna com tempero gourmet mineiro",
    featuredHandle: "temperaflix-tradicional",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "120 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["2kg costela", "80g Temperaflix Tradicional", "200ml cerveja", "100ml caldo beef"],
    steps: ["Tempere costela com Temperaflix Tradicional.", "Asse a 160°C com cerveja e caldo por 2 horas."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Tradicional.",
    whyItWorks: "Costela morna com tempero gourmet mineiro",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "picadinho-a-mineira-com-tempero-mineiro",
    title: "Picadinho à Mineira com Tempero Mineiro",
    subtitle: "Clássico mineiro com carnes e vegetais",
    intro: "Clássico mineiro com carnes e vegetais",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "40 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["600g carne moída", "1 cebola", "3 tomates", "1 xícara ervilha", "50g Tempero Mineiro"],
    steps: ["Refogue cebola e carne.", "Adicione tomates e ervilha.", "Tempere com Tempero Mineiro.", "Cozinhe 30 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Tempero Mineiro.",
    whyItWorks: "Clássico mineiro com carnes e vegetais",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-em-brasa-com-chimi-churri-suave",
    title: "Frango em Brasa com Chimi Churri Suave",
    subtitle: "Frango grelhado com chimichurri sem pimenta",
    intro: "Frango grelhado com chimichurri sem pimenta",
    featuredHandle: "chimichurri-sem-pimenta",
    compatibleDiets: [],
    moment: "almoco",
    profile: "citrico-picante",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1kg frango em cubos", "70g Chimi Churri Sem Pimenta", "100ml azeite"],
    steps: ["Tempere frango.", "Grelhe em brasa.", "Faça molho: Chimi Churri Sem Pimenta + azeite.", "Sirva."],
    chefWord: "Um preparo pensado para destacar o sabor de Chimi Churri Sem Pimenta.",
    whyItWorks: "Frango grelhado com chimichurri sem pimenta",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "frango",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bife-a-pizzaiola-com-paprica-picante",
    title: "Bife à Pizzaiola com Páprica Picante",
    subtitle: "Bife clássico italiano com tomate e páprica vermelha",
    intro: "Bife clássico italiano com tomate e páprica vermelha",
    featuredHandle: "paprica-picante",
    compatibleDiets: [],
    moment: "almoco",
    profile: "citrico-picante",
    category: "tradicional",
    time: "35 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["400g contrafilé", "400g tomate", "2 dentes alho", "40g Páprica Picante", "50ml azeite"],
    steps: ["Grelhe bife.", "Faça molho com tomate, alho e Páprica Picante.", "Despeje sobre o bife."],
    chefWord: "Um preparo pensado para destacar o sabor de Páprica Picante.",
    whyItWorks: "Bife clássico italiano com tomate e páprica vermelha",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "moqueca-de-peixe-com-salsa-cebola-e-alho",
    title: "Moqueca de Peixe com Salsa Cebola e Alho",
    subtitle: "Prato baiano com peixe e tempero aromático",
    intro: "Prato baiano com peixe e tempero aromático",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "almoco",
    profile: "ervas",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["800g peixe branco", "2 cebolas", "1 pimentão", "200ml leite de coco", "50g Salsa Cebola e Alho"],
    steps: ["Refogue cebola, pimentão e alho.", "Adicione peixe e leite de coco.", "Finalize com Salsa Cebola e Alho."],
    chefWord: "Um preparo pensado para destacar o sabor de Salsa Cebola e Alho.",
    whyItWorks: "Prato baiano com peixe e tempero aromático",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "pescados",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bifao-com-paprica-doce-e-cebola",
    title: "Bifão com Páprica Doce e Cebola",
    subtitle: "Bifão morno com cebola caramelizada e páprica suave",
    intro: "Bifão morno com cebola caramelizada e páprica suave",
    featuredHandle: "paprica-doce",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "35 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["400g paleta", "3 cebolas", "50g Páprica Doce", "50ml azeite"],
    steps: ["Grelhe bifão.", "Caramelize cebolas separadas.", "Misture com Páprica Doce e azeite.", "Sirva sobre o bifão."],
    chefWord: "Um preparo pensado para destacar o sabor de Páprica Doce.",
    whyItWorks: "Bifão morno com cebola caramelizada e páprica suave",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ragu-de-carne-com-temperaflix-bacon",
    title: "Ragu de Carne com Temperaflix Bacon",
    subtitle: "Molho tradicional italiano com toque de bacon defumado",
    intro: "Molho tradicional italiano com toque de bacon defumado",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "almoco",
    profile: "defumado",
    category: "tradicional",
    time: "90 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["500g carne moída", "400g tomate pelado", "1 cebola", "3 dentes alho", "60g Temperaflix Bacon"],
    steps: ["Refogue carne, cebola e alho.", "Adicione tomate.", "Cozinhe 1 hora.", "Finalize com Temperaflix Bacon."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Bacon.",
    whyItWorks: "Molho tradicional italiano com toque de bacon defumado",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "galinhada-mineira-com-edu-guedes",
    title: "Galinhada Mineira com Edu Guedes",
    subtitle: "Prato mineiro tradicional com galinha e tempero versátil",
    intro: "Prato mineiro tradicional com galinha e tempero versátil",
    featuredHandle: "tempero-do-edu",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "75 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["1 galinha picada", "2 xícaras arroz", "1 cebola", "200ml caldo chicken", "50g Edu Guedes"],
    steps: ["Cozinhe galinha com cebola.", "Adicione arroz e caldo.", "Cozinhe 45 min.", "Finalize com Edu Guedes."],
    chefWord: "Um preparo pensado para destacar o sabor de Edu Guedes.",
    whyItWorks: "Prato mineiro tradicional com galinha e tempero versátil",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "frango",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "feijoada-a-mineira-com-temperaflix-ervas-finas",
    title: "Feijoada à Mineira com Temperaflix Ervas Finas",
    subtitle: "Clássico mineiro com ervas aromáticas premium",
    intro: "Clássico mineiro com ervas aromáticas premium",
    featuredHandle: "temperaflix-ervas-finas",
    compatibleDiets: [],
    moment: "almoco",
    profile: "ervas",
    category: "tradicional",
    time: "120 min",
    serves: "6 porções",
    difficulty: "Médio",
    ingredients: ["500g feijão preto", "400g carne de porco", "1 cebola", "200g toucinho", "60g Temperaflix Ervas Finas"],
    steps: ["Cozinhe feijão com carnes.", "Refogue cebola e toucinho.", "Misture tudo.", "Finalize com Temperaflix Ervas Finas."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Ervas Finas.",
    whyItWorks: "Clássico mineiro com ervas aromáticas premium",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "strogonoff-de-carne-com-ana-maria",
    title: "Strogonoff de Carne com Ana Maria",
    subtitle: "Prato clássico brasileiro com tempero mineiro",
    intro: "Prato clássico brasileiro com tempero mineiro",
    featuredHandle: "ana-maria",
    compatibleDiets: [],
    moment: "almoco",
    profile: "casa",
    category: "tradicional",
    time: "40 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["600g carne contra filé", "1 cebola", "1 xícara creme", "100g cogumelo", "50g Ana Maria"],
    steps: ["Refogue carne, cebola e cogumelo.", "Adicione creme.", "Tempere com Ana Maria.", "Cozinhe 20 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Ana Maria.",
    whyItWorks: "Prato clássico brasileiro com tempero mineiro",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "peixe-grelhado-com-ervas-finas",
    title: "Peixe Grelhado com Ervas Finas",
    subtitle: "Peixe delicado temperado com ervas desidratadas premium",
    intro: "Peixe delicado temperado com ervas desidratadas premium",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "25 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["800g filé de peixe branco", "50g Ervas Finas", "50ml azeite", "2 limões"],
    steps: ["Grelhe peixe temperado com Ervas Finas, azeite e suco de limão por 15 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Ervas Finas.",
    whyItWorks: "Peixe delicado temperado com ervas desidratadas premium",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "pescados",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "frango-leve-com-curcuma-e-gengibre",
    title: "Frango Leve com Cúrcuma e Gengibre",
    subtitle: "Frango assado leve com toque anti-inflamatório",
    intro: "Frango assado leve com toque anti-inflamatório",
    featuredHandle: "curcuma",
    compatibleDiets: [],
    moment: "jantar",
    profile: "puras",
    category: "tradicional",
    time: "50 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["800g filé de frango", "40g Cúrcuma", "2 colheres gengibre", "100ml caldo light"],
    steps: ["Asse frango com Cúrcuma e gengibre a 190°C por 40 min com caldo leve."],
    chefWord: "Um preparo pensado para destacar o sabor de Cúrcuma.",
    whyItWorks: "Frango assado leve com toque anti-inflamatório",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "frango",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "salmao-ao-forno-com-lemon-pepper",
    title: "Salmão ao Forno com Lemon Pepper",
    subtitle: "Salmão fresco com toque de pimenta preta e limão",
    intro: "Salmão fresco com toque de pimenta preta e limão",
    featuredHandle: "lemon-pepper",
    compatibleDiets: [],
    moment: "jantar",
    profile: "citrico-picante",
    category: "tradicional",
    time: "30 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["400g filé salmão", "40g Lemon Pepper", "50ml azeite", "2 limões"],
    steps: ["Coloque salmão em papel alumínio.", "Cubra com Lemon Pepper, azeite e limão.", "Asse a 200°C por 25 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Lemon Pepper.",
    whyItWorks: "Salmão fresco com toque de pimenta preta e limão",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "pescados",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "carne-magra-grelhada-com-salsa-cebola-e-alho",
    title: "Carne Magra Grelhada com Salsa Cebola e Alho",
    subtitle: "Carne magra leve com tempero aromático",
    intro: "Carne magra leve com tempero aromático",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "20 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["300g paleta magra", "40g Salsa Cebola e Alho", "30ml azeite"],
    steps: ["Grelhe carne magra.", "Tempere com Salsa Cebola e Alho e azeite.", "Sirva leve."],
    chefWord: "Um preparo pensado para destacar o sabor de Salsa Cebola e Alho.",
    whyItWorks: "Carne magra leve com tempero aromático",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "peito-de-frango-com-temperaflix-bacon-leve",
    title: "Peito de Frango com Temperaflix Bacon Leve",
    subtitle: "Frango light com toque de bacon defumado",
    intro: "Frango light com toque de bacon defumado",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "jantar",
    profile: "defumado",
    category: "tradicional",
    time: "35 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["400g peito de frango", "40g Temperaflix Bacon", "50ml água", "20ml azeite"],
    steps: ["Refogue frango em pouca gordura.", "Adicione água e Temperaflix Bacon.", "Cozinhe 25 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Bacon.",
    whyItWorks: "Frango light com toque de bacon defumado",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "frango",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "vegetais-leves-com-edu-guedes",
    title: "Vegetais Leves com Edu Guedes",
    subtitle: "Mix de vegetais cozidos no vapor com tempero versátil",
    intro: "Mix de vegetais cozidos no vapor com tempero versátil",
    featuredHandle: "tempero-do-edu",
    compatibleDiets: [],
    moment: "jantar",
    profile: "casa",
    category: "tradicional",
    time: "25 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["200g cenoura", "200g brócolis", "150g abobrinha", "40g Edu Guedes", "20ml azeite"],
    steps: ["Cozinhe vegetais no vapor.", "Tempere com Edu Guedes e azeite.", "Sirva morno."],
    chefWord: "Um preparo pensado para destacar o sabor de Edu Guedes.",
    whyItWorks: "Mix de vegetais cozidos no vapor com tempero versátil",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "caldo-de-carne-temperado-com-tempero-mineiro",
    title: "Caldo de Carne Temperado com Tempero Mineiro",
    subtitle: "Caldo quentinho com tempero mineiro tradicional",
    intro: "Caldo quentinho com tempero mineiro tradicional",
    featuredHandle: "tempero-mineiro",
    compatibleDiets: [],
    moment: "jantar",
    profile: "casa",
    category: "tradicional",
    time: "60 min",
    serves: "4 porções",
    difficulty: "Médio",
    ingredients: ["800ml caldo beef", "300g carne picada", "1 batata", "1 cenoura", "50g Tempero Mineiro"],
    steps: ["Cozinhe caldo com carne.", "Adicione batata e cenoura.", "Tempere com Tempero Mineiro."],
    chefWord: "Um preparo pensado para destacar o sabor de Tempero Mineiro.",
    whyItWorks: "Caldo quentinho com tempero mineiro tradicional",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "bovina",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "moqueca-leve-de-peixe-com-paprica-defumada",
    title: "Moqueca Leve de Peixe com Páprica Defumada",
    subtitle: "Peixe em caldo leve com páprica defumada",
    intro: "Peixe em caldo leve com páprica defumada",
    featuredHandle: "paprica-defumada",
    compatibleDiets: [],
    moment: "jantar",
    profile: "defumado",
    category: "tradicional",
    time: "40 min",
    serves: "2 porções",
    difficulty: "Fácil",
    ingredients: ["400g peixe branco", "200ml caldo leve", "1 cebola", "40g Páprica Defumada"],
    steps: ["Cozinhe peixe em caldo com cebola.", "Finalize com Páprica Defumada."],
    chefWord: "Um preparo pensado para destacar o sabor de Páprica Defumada.",
    whyItWorks: "Peixe em caldo leve com páprica defumada",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "pescados",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "sopa-cremosa-com-temperaflix-ervas-finas",
    title: "Sopa Cremosa com Temperaflix Ervas Finas",
    subtitle: "Sopa cremosa e reconfortante com ervas premium",
    intro: "Sopa cremosa e reconfortante com ervas premium",
    featuredHandle: "temperaflix-ervas-finas",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "45 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1L caldo vegetal", "300g abóbora", "200g cenoura", "200ml creme", "50g Temperaflix Ervas Finas"],
    steps: ["Cozinhe abóbora e cenoura.", "Bata com caldo.", "Adicione creme e Temperaflix Ervas Finas."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Ervas Finas.",
    whyItWorks: "Sopa cremosa e reconfortante com ervas premium",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "ovo-poche-com-ervas-finas-e-pao-integral",
    title: "Ovo Poché com Ervas Finas e Pão Integral",
    subtitle: "Ovo poché leve com ervas aromáticas",
    intro: "Ovo poché leve com ervas aromáticas",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "jantar",
    profile: "ervas",
    category: "tradicional",
    time: "15 min",
    serves: "1 porções",
    difficulty: "Fácil",
    ingredients: ["2 ovos", "30g Ervas Finas", "1 fatia pão integral", "20ml azeite"],
    steps: ["Cozinhe ovos em água morna.", "Coloque em pão.", "Finalize com Ervas Finas e azeite."],
    chefWord: "Um preparo pensado para destacar o sabor de Ervas Finas.",
    whyItWorks: "Ovo poché leve com ervas aromáticas",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "ovo",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "hummus-com-temperaflix-tradicional",
    title: "Hummus com Temperaflix Tradicional",
    subtitle: "Pasta de grão-de-bico com toque gourmet mineiro",
    intro: "Pasta de grão-de-bico com toque gourmet mineiro",
    featuredHandle: "temperaflix-tradicional",
    compatibleDiets: [],
    moment: "lanche",
    profile: "casa",
    category: "tradicional",
    time: "20 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["400g grão-de-bico cozido", "50ml azeite", "2 colheres tahine", "50g Temperaflix Tradicional"],
    steps: ["Bata todos os ingredientes até cremoso.", "Sirva com pão árabe ou vegetais."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Tradicional.",
    whyItWorks: "Pasta de grão-de-bico com toque gourmet mineiro",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "guacamole-com-chimi-churri-picante",
    title: "Guacamole com Chimi Churri Picante",
    subtitle: "Guacamole fresco com chimichurri argentino",
    intro: "Guacamole fresco com chimichurri argentino",
    featuredHandle: "chimichurri-picante",
    compatibleDiets: [],
    moment: "lanche",
    profile: "citrico-picante",
    category: "tradicional",
    time: "10 min",
    serves: "3 porções",
    difficulty: "Fácil",
    ingredients: ["3 abacates", "1 limão", "1 tomate", "30g Chimi Churri Picante"],
    steps: ["Amasse abacates com suco de limão.", "Adicione tomate picado e Chimi Churri Picante.", "Sirva."],
    chefWord: "Um preparo pensado para destacar o sabor de Chimi Churri Picante.",
    whyItWorks: "Guacamole fresco com chimichurri argentino",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "iogurte-com-granola-e-lemon-pepper",
    title: "Iogurte com Granola e Lemon Pepper",
    subtitle: "Iogurte grego com granola crocante e toque cítrico",
    intro: "Iogurte grego com granola crocante e toque cítrico",
    featuredHandle: "lemon-pepper",
    compatibleDiets: [],
    moment: "lanche",
    profile: "citrico-picante",
    category: "tradicional",
    time: "5 min",
    serves: "1 porções",
    difficulty: "Fácil",
    ingredients: ["150g iogurte grego", "50g granola", "30g Lemon Pepper"],
    steps: ["Coloque iogurte em tigela.", "Adicione granola e finalize com Lemon Pepper."],
    chefWord: "Um preparo pensado para destacar o sabor de Lemon Pepper.",
    whyItWorks: "Iogurte grego com granola crocante e toque cítrico",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "queijo-com-ervas-finas-e-cracker",
    title: "Queijo com Ervas Finas e Cracker",
    subtitle: "Tábua de queijo temperado com ervas aromaáticas",
    intro: "Tábua de queijo temperado com ervas aromaáticas",
    featuredHandle: "ervas-finas",
    compatibleDiets: [],
    moment: "lanche",
    profile: "ervas",
    category: "tradicional",
    time: "10 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["200g queijo meia cura", "40g Ervas Finas", "100g cracker integral"],
    steps: ["Corte queijo em cubos.", "Polvilhe com Ervas Finas.", "Sirva com cracker."],
    chefWord: "Um preparo pensado para destacar o sabor de Ervas Finas.",
    whyItWorks: "Tábua de queijo temperado com ervas aromaáticas",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "mix-de-oleaginosas-com-paprica-picante",
    title: "Mix de Oleaginosas com Páprica Picante",
    subtitle: "Mix de castanhas e sementes com páprica vermelha",
    intro: "Mix de castanhas e sementes com páprica vermelha",
    featuredHandle: "paprica-picante",
    compatibleDiets: [],
    moment: "lanche",
    profile: "citrico-picante",
    category: "tradicional",
    time: "5 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["100g castanha de caju", "100g amêndoas", "50g sementes de girassol", "30g Páprica Picante"],
    steps: ["Misture oleaginosas.", "Polvilhe Páprica Picante.", "Sirva em porções pequenas."],
    chefWord: "Um preparo pensado para destacar o sabor de Páprica Picante.",
    whyItWorks: "Mix de castanhas e sementes com páprica vermelha",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "batatinha-chips-caseira-com-ana-maria",
    title: "Batatinha Chips Caseira com Ana Maria",
    subtitle: "Batata chips crocante com tempero mineiro",
    intro: "Batata chips crocante com tempero mineiro",
    featuredHandle: "ana-maria",
    compatibleDiets: [],
    moment: "lanche",
    profile: "casa",
    category: "tradicional",
    time: "35 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["4 batatas médias", "40g Ana Maria", "500ml óleo para fritar"],
    steps: ["Corte batatas em fatias finas.", "Frite até dourar.", "Tempere com Ana Maria ainda quentes."],
    chefWord: "Um preparo pensado para destacar o sabor de Ana Maria.",
    whyItWorks: "Batata chips crocante com tempero mineiro",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bruschetone-com-tomate-e-salsa-cebola-e-alho",
    title: "Bruschetone com Tomate e Salsa Cebola e Alho",
    subtitle: "Bruschetone tradicional italiano com tempero aromático",
    intro: "Bruschetone tradicional italiano com tempero aromático",
    featuredHandle: "salsa-cebola-e-alho",
    compatibleDiets: [],
    moment: "lanche",
    profile: "ervas",
    category: "tradicional",
    time: "15 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["1 baguete", "400g tomate fresco", "40g Salsa Cebola e Alho", "50ml azeite"],
    steps: ["Toste baguete.", "Misture tomate com Salsa Cebola e Alho e azeite.", "Coloque sobre o pão."],
    chefWord: "Um preparo pensado para destacar o sabor de Salsa Cebola e Alho.",
    whyItWorks: "Bruschetone tradicional italiano com tempero aromático",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "amendoim-crocante-com-temperaflix-bacon",
    title: "Amendoim Crocante com Temperaflix Bacon",
    subtitle: "Amendoim crocante com toque de bacon defumado",
    intro: "Amendoim crocante com toque de bacon defumado",
    featuredHandle: "temperaflix-bacon",
    compatibleDiets: [],
    moment: "lanche",
    profile: "defumado",
    category: "tradicional",
    time: "25 min",
    serves: "4 porções",
    difficulty: "Fácil",
    ingredients: ["300g amendoim descascado", "40g Temperaflix Bacon", "30ml azeite", "Sal"],
    steps: ["Torça amendoim em forno a 180°C por 20 min.", "Misture com azeite e Temperaflix Bacon.", "Sirva."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Bacon.",
    whyItWorks: "Amendoim crocante com toque de bacon defumado",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bolo-de-chocolate-com-paprica-doce",
    title: "Bolo de Chocolate com Páprica Doce",
    subtitle: "Bolo de chocolate com toque doce e sutil de páprica",
    intro: "Bolo de chocolate com toque doce e sutil de páprica",
    featuredHandle: "paprica-doce",
    compatibleDiets: [],
    moment: "lanche",
    profile: "defumado",
    category: "tradicional",
    time: "40 min",
    serves: "8 porções",
    difficulty: "Fácil",
    ingredients: ["200g chocolate amargo", "150g açúcar", "3 ovos", "200ml leite", "30g Páprica Doce"],
    steps: ["Derreta chocolate com manteiga.", "Misture ovos, açúcar e leite.", "Adicione Páprica Doce.", "Asse a 180°C por 35 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Páprica Doce.",
    whyItWorks: "Bolo de chocolate com toque doce e sutil de páprica",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "bolo-de-chocolate-com-temperaflix-ervas-finas",
    title: "Bolo de Chocolate com Temperaflix Ervas Finas",
    subtitle: "Bolo de chocolate com toque herbal premium",
    intro: "Bolo de chocolate com toque herbal premium",
    featuredHandle: "temperaflix-ervas-finas",
    compatibleDiets: [],
    moment: "lanche",
    profile: "ervas",
    category: "tradicional",
    time: "40 min",
    serves: "8 porções",
    difficulty: "Fácil",
    ingredients: ["200g chocolate amargo", "150g açúcar", "3 ovos", "200ml leite", "30g Temperaflix Ervas Finas"],
    steps: ["Derreta chocolate com manteiga.", "Misture ovos, açúcar e leite.", "Adicione Temperaflix Ervas Finas.", "Asse a 180°C por 35 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Temperaflix Ervas Finas.",
    whyItWorks: "Bolo de chocolate com toque herbal premium",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "paes",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
  {
    slug: "biscoito-de-curcuma-e-gengibre",
    title: "Biscoito de Cúrcuma e Gengibre",
    subtitle: "Biscoito aromático anti-inflamatório",
    intro: "Biscoito aromático anti-inflamatório",
    featuredHandle: "curcuma",
    compatibleDiets: [],
    moment: "lanche",
    profile: "puras",
    category: "tradicional",
    time: "30 min",
    serves: "12 porções",
    difficulty: "Fácil",
    ingredients: ["200g farinha", "100g manteiga", "100g açúcar", "1 ovo", "40g Cúrcuma"],
    steps: ["Bata manteiga com açúcar.", "Adicione ovo, farinha e Cúrcuma.", "Asse a 180°C por 20 min."],
    chefWord: "Um preparo pensado para destacar o sabor de Cúrcuma.",
    whyItWorks: "Biscoito aromático anti-inflamatório",
    substitution: "Ajuste sal, acidez e intensidade do condimento ao seu paladar.",
    proteinaPrincipal: "vegetariano",
    hero: { color: "oklch(0.52 0.21 28)" },
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return RECIPES.find((recipe) => recipe.slug === slug);
}

export function getRecipesByHandle(handle: string): Recipe[] {
  return RECIPES.filter((recipe) => recipe.featuredHandle === handle);
}

export type Protein = "frango" | "bovina" | "suino" | "pescados" | "ovo" | "paes" | "vegetariano";

export const PROTEINS: Record<Protein, string> = {
  frango: "Frango",
  bovina: "Carne bovina",
  suino: "Suíno",
  pescados: "Peixe & Frutos do Mar",
  ovo: "Ovo",
  paes: "Pães",
  vegetariano: "Vegetariano",
};

export const PROTEIN_ORDER: Protein[] = ["frango", "bovina", "suino", "pescados", "ovo", "paes", "vegetariano"];
export const RECIPE_PROTEIN: Record<string, Protein> = Object.fromEntries(RECIPES.map((recipe) => [recipe.slug, recipe.proteinaPrincipal ?? "vegetariano"]));
export function getRecipeProtein(recipe: Recipe): Protein | undefined {
  return recipe.proteinaPrincipal ?? RECIPE_PROTEIN[recipe.slug];
}
