import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Loader2, Minus, Plus, ShoppingBag } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { CombinaCom } from "@/components/site/CombinaCom";
import { DietCompatibilityPanel } from "@/components/site/DietCompatibilityPanel";
import { FlavorTiles } from "@/components/site/FlavorTiles";
import { ProductTrust } from "@/components/site/ProductTrust";
import { getProductDiet } from "@/lib/dietCompatibility";
import { getProductImage, resolveProductImage } from "@/lib/productImages";
import { getProductStageGeometry } from "@/lib/productVisualStage";
import { isRebrandEligibleHandle } from "@/lib/rebrandCatalog";
import { getRecipesByHandle } from "@/lib/recipes";
import { trackEvent, toAnalyticsItem } from "@/lib/analytics";
import { formatBRL, PRODUCT_BY_HANDLE_QUERY, STOREFRONT_QUERY, storefrontApiRequest, type ShopifyProduct } from "@/lib/shopify";
import { useCartStore } from "@/stores/cartStore";
const SITE_URL="https://temperanzza.com.br";
interface ProductNode{id:string;title:string;description:string;handle:string;priceRange:{minVariantPrice:{amount:string;currencyCode:string}};images:{edges:Array<{node:{url:string;altText:string|null}}>};variants:{edges:Array<{node:{id:string;title:string;price:{amount:string;currencyCode:string};availableForSale:boolean;selectedOptions:Array<{name:string;value:string}>}}>};}
function toAbsoluteUrl(url?:string|null){if(!url)return undefined;return url.startsWith("http")?url:`${SITE_URL}${url.startsWith("/")?"":"/"}${url}`;}
const productQueryOptions=(handle:string)=>queryOptions({queryKey:["product",handle],queryFn:async():Promise<ProductNode>=>{const res=await storefrontApiRequest(PRODUCT_BY_HANDLE_QUERY,{handle});const p=res?.data?.productByHandle;if(!p)throw notFound();return p as ProductNode;}});
export const Route=createFileRoute("/product/$handle")({loader:({params,context})=>{if(!isRebrandEligibleHandle(params.handle))throw notFound();return context.queryClient.ensureQueryData(productQueryOptions(params.handle));},head:({params,loaderData})=>{const p=loaderData as ProductNode|undefined,url=`${SITE_URL}/product/${params.handle}`;if(!p)return{meta:[{title:`${params.handle} — Temperanzza`}],links:[{rel:"canonical",href:url}]};const description=(p.description||`${p.title} — condimento Temperanzza.`).replace(/\s+/g," ").trim().slice(0,160),image=toAbsoluteUrl(getProductImage(p.handle))??toAbsoluteUrl(p.images.edges[0]?.node.url),price=p.priceRange.minVariantPrice,available=p.variants.edges.some((v)=>v.node.availableForSale);return{meta:[{title:`${p.title} — Temperanzza | Condimentos de Minas Gerais`},{name:"description",content:description},{property:"og:title",content:`${p.title} — Temperanzza`},{property:"og:description",content:description},{property:"og:type",content:"product"},{property:"og:url",content:url},...(image?[{property:"og:image",content:image},{name:"twitter:card",content:"summary_large_image"}]:[])],links:[{rel:"canonical",href:url},...(image?[{rel:"preload",as:"image" as const,href:image,fetchpriority:"high"}]:[])],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Product",name:p.title,description,image,sku:p.handle,brand:{"@type":"Brand",name:"Temperanzza"},category:"Temperos e Especiarias",offers:{"@type":"Offer",url,priceCurrency:price.currencyCode,price:price.amount,availability:available?"https://schema.org/InStock":"https://schema.org/OutOfStock",itemCondition:"https://schema.org/NewCondition"}})}]};},component:ProductPage,notFoundComponent:()=> <StatePage title="Produto não encontrado"/>,errorComponent:()=> <StatePage title="Erro ao carregar"/>});
function StatePage({title}:{title:string}){return <div className="grid min-h-[60vh] place-items-center bg-brand-paper px-6 text-center"><div><h1 className="font-display text-4xl">{title}</h1><Link to="/produtos" className="mt-6 inline-block underline underline-offset-4">Voltar ao catálogo</Link></div></div>;}
function ProductPage(){
 const{handle}=Route.useParams();const[qty,setQty]=useState(1),[imgIdx,setImgIdx]=useState(0);const addItem=useCartStore((s)=>s.addItem),isLoading=useCartStore((s)=>s.isLoading);const{data:product,isLoading:loadingProduct}=useQuery(productQueryOptions(handle));const{data:allProducts}=useQuery({queryKey:["shopify-products",24],queryFn:async()=>{const res=await storefrontApiRequest(STOREFRONT_QUERY,{first:24,query:null});return((res?.data?.products?.edges??[])as ShopifyProduct[]).filter((p)=>isRebrandEligibleHandle(p.node.handle));}});
 useEffect(()=>{if(product)trackEvent("view_item",{currency:product.priceRange.minVariantPrice.currencyCode,value:parseFloat(product.priceRange.minVariantPrice.amount),items:[toAnalyticsItem({handle,title:product.title,price:product.priceRange.minVariantPrice.amount})]});},[product,handle]);
 if(loadingProduct)return <div className="grid min-h-[60vh] place-items-center bg-brand-paper"><Loader2 className="h-7 w-7 animate-spin"/></div>;if(!product)return null;
 const variant=product.variants.edges[0]?.node,images=product.images.edges,mainImage=images[imgIdx]?.node??images[0]?.node,resolution=resolveProductImage(handle,mainImage?.url),recipes=getRecipesByHandle(handle),diet=getProductDiet(handle),geometry=getProductStageGeometry(handle,"pdp");
 const handleAdd=async()=>{if(!variant)return;await addItem({product:{node:product},variantId:variant.id,variantTitle:variant.title,price:variant.price,quantity:qty,selectedOptions:variant.selectedOptions||[]});trackEvent("add_to_cart",{currency:variant.price.currencyCode,value:parseFloat(variant.price.amount)*qty,items:[toAnalyticsItem({handle,title:product.title,price:variant.price.amount,quantity:qty})]});toast.success(`${product.title} adicionado à sacola`);};
 return <div className="min-h-screen bg-white text-brand-ink"><main><section className="page-shell py-6 sm:py-10"><Link to="/produtos" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-brand-ink/60 hover:text-brand-ink"><ArrowLeft className="h-4 w-4"/>Voltar aos sabores</Link><div className="grid items-start gap-10 lg:grid-cols-[1.12fr_.88fr] lg:gap-20"><div className="lg:sticky lg:top-24"><div className="relative min-h-[500px] overflow-hidden bg-[#f7f6f2] sm:min-h-[650px]" data-product-stage={handle} data-image-source={resolution.source}><div aria-hidden className={`absolute left-1/2 -translate-x-1/2 rounded-full bg-black/10 blur-xl ${geometry.shadowClass}`}/>{resolution.url&&<img src={resolution.url} alt={mainImage?.altText||product.title} data-product-handle={handle} data-image-source={resolution.source} fetchPriority="high" decoding="async" className={`absolute inset-0 m-auto object-contain drop-shadow-[0_24px_24px_rgba(0,0,0,.13)] animate-product-enter ${geometry.imageClass}`}/>}</div>{images.length>1&&<div className="mt-4 flex gap-3 overflow-x-auto pb-2">{images.map((img,i)=>{const r=resolveProductImage(handle,img.node.url);return <button key={img.node.url} onClick={()=>setImgIdx(i)} aria-label={`Ver imagem ${i+1}`} aria-pressed={i===imgIdx} className={`relative h-20 w-20 shrink-0 overflow-hidden border bg-white ${i===imgIdx?"border-brand-ink":"border-brand-ink/10"}`}>{r.url&&<img src={r.url} alt="" data-image-source={r.source} className="absolute inset-0 m-auto h-[82%] w-[76%] object-contain"/>}</button>;})}</div>}</div>
 <div className="py-2 lg:py-12"><span className="text-xs font-semibold uppercase tracking-[.24em] text-muted-foreground">Casa Temperanzza</span><h1 className="mt-4 font-display text-[clamp(3.2rem,6vw,6.4rem)] font-semibold leading-[.86] tracking-tight">{product.title}</h1><p className="mt-7 text-2xl font-semibold tabular-nums">{formatBRL(product.priceRange.minVariantPrice.amount,product.priceRange.minVariantPrice.currencyCode)}</p>{product.description&&<p className="mt-7 max-w-xl whitespace-pre-line text-base leading-7 text-brand-ink/68 sm:text-lg sm:leading-8">{product.description}</p>}{variant?.title&&variant.title!=="Default Title"&&<div className="mt-8 border-y border-brand-ink/10 py-4"><span className="text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">Tamanho</span><p className="mt-1 font-semibold">{variant.title}</p></div>}<div className="mt-9 flex flex-col gap-3 sm:flex-row"><div className="flex h-14 items-center justify-between border border-brand-ink/15 sm:w-40"><Button variant="ghost" size="icon" className="h-12 w-12 rounded-none" onClick={()=>setQty(Math.max(1,qty-1))} aria-label="Diminuir quantidade"><Minus className="h-4 w-4"/></Button><span className="font-semibold">{qty}</span><Button variant="ghost" size="icon" className="h-12 w-12 rounded-none" onClick={()=>setQty(qty+1)} aria-label="Aumentar quantidade"><Plus className="h-4 w-4"/></Button></div><Button onClick={handleAdd} disabled={isLoading||!variant?.availableForSale} className="h-14 flex-1 rounded-none bg-brand-ink px-7 text-brand-paper hover:bg-brand-ink/90">{isLoading?<Loader2 className="h-4 w-4 animate-spin"/>:<><ShoppingBag className="mr-2 h-4 w-4"/>Adicionar à sacola</>}</Button></div>{variant&&!variant.availableForSale&&<p className="mt-3 text-sm font-semibold">Esgotado no momento</p>}<p className="mt-5 text-xs leading-5 text-muted-foreground">Embalado lote a lote em Minas Gerais · Envio calculado no fechamento do pedido.</p>{allProducts&&allProducts.length>1&&<div className="mt-12"><FlavorTiles products={allProducts} currentHandle={handle}/></div>}</div></div></section>
 <section className="mt-12 border-y border-brand-ink/10 bg-brand-paper py-16 sm:py-24"><div className="page-shell"><ProductTrust handle={handle} title={product.title}/></div></section>
 {recipes.length>0&&<section className="section-space bg-white"><div className="page-shell"><div className="mb-10 flex items-end justify-between gap-6"><div><span className="text-xs font-semibold uppercase tracking-[.22em] text-muted-foreground">Na Cozinha Temperanzza</span><h2 className="mt-3 font-display text-4xl font-semibold sm:text-6xl">Receitas com {product.title}</h2></div><Link to="/cozinha" search={{refeicao:"",proteina:"",lifestyle:"",autor:""}} className="hidden items-center gap-2 border-b border-brand-ink/25 pb-1 text-sm font-semibold sm:inline-flex">Todas as receitas <ArrowUpRight className="h-4 w-4"/></Link></div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{recipes.slice(0,3).map((r)=><Link key={r.slug} to="/cozinha/$slug" params={{slug:r.slug}} search={{refeicao:"",proteina:"",lifestyle:"",autor:""}} className="group"><div className="aspect-[4/3] overflow-hidden bg-brand-cream">{r.dish&&<img src={r.dish.src} alt={r.dish.alt} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]"/>}</div><h3 className="mt-5 font-display text-3xl font-semibold leading-none">{r.title}</h3><span className="mt-4 inline-flex items-center gap-2 border-b border-brand-ink/25 pb-1 text-xs font-semibold">Ver receita <ArrowUpRight className="h-3.5 w-3.5"/></span></Link>)}</div></div></section>}
 <div className="page-shell section-space">{diet&&<DietCompatibilityPanel diet={diet}/>} {allProducts&&allProducts.length>1&&<CombinaCom currentHandle={handle} products={allProducts}/>}</div></main></div>;
}
