import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { ArrowLeft, BookOpen, Loader2, Minus, Plus, ShoppingBag } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { CombinaCom } from "@/components/site/CombinaCom";
import { DietCompatibilityPanel } from "@/components/site/DietCompatibilityPanel";
import { FlavorTiles } from "@/components/site/FlavorTiles";
import { ProductTrust } from "@/components/site/ProductTrust";
import { getProductDiet } from "@/lib/dietCompatibility";
import { getFlavorTone } from "@/lib/flavorPalette";
import { getProductImage, resolveProductImage } from "@/lib/productImages";
import { getProductStageGeometry } from "@/lib/productVisualStage";
import { isRebrandExcludedHandle } from "@/lib/rebrandCatalog";
import { getRecipesByHandle } from "@/lib/recipes";
import { trackEvent, toAnalyticsItem } from "@/lib/analytics";
import { formatBRL, PRODUCT_BY_HANDLE_QUERY, STOREFRONT_QUERY, storefrontApiRequest, type ShopifyProduct } from "@/lib/shopify";
import { useCartStore } from "@/stores/cartStore";

const SITE_URL = "https://temperanzza.com.br";
interface ProductNode { id: string; title: string; description: string; handle: string; priceRange: { minVariantPrice: { amount: string; currencyCode: string } }; images: { edges: Array<{ node: { url: string; altText: string | null } }> }; variants: { edges: Array<{ node: { id: string; title: string; price: { amount: string; currencyCode: string }; availableForSale: boolean; selectedOptions: Array<{ name: string; value: string }> } }> }; }
function toAbsoluteUrl(url?: string | null) { if (!url) return undefined; return url.startsWith("http") ? url : `${SITE_URL}${url.startsWith("/") ? "" : "/"}${url}`; }
const productQueryOptions = (handle: string) => queryOptions({ queryKey: ["product", handle], queryFn: async (): Promise<ProductNode> => { const res = await storefrontApiRequest(PRODUCT_BY_HANDLE_QUERY, { handle }); const p = res?.data?.productByHandle; if (!p) throw notFound(); return p as ProductNode; } });

export const Route = createFileRoute("/product/$handle")({ loader: ({ params, context }) => { if (isRebrandExcludedHandle(params.handle)) throw notFound(); return context.queryClient.ensureQueryData(productQueryOptions(params.handle)); }, head: ({ params, loaderData }) => { const p = loaderData as ProductNode | undefined; const url = `${SITE_URL}/product/${params.handle}`; if (!p) return { meta: [{ title: `${params.handle} — Temperanzza` }], links: [{ rel: "canonical", href: url }] }; const description = (p.description || `${p.title} — condimento Temperanzza.`).replace(/\s+/g, " ").trim().slice(0, 160); const image = toAbsoluteUrl(getProductImage(p.handle)) ?? toAbsoluteUrl(p.images.edges[0]?.node.url); const price = p.priceRange.minVariantPrice; const available = p.variants.edges.some((v) => v.node.availableForSale); const productLd = { "@context": "https://schema.org", "@type": "Product", name: p.title, description, image, sku: p.handle, brand: { "@type": "Brand", name: "Temperanzza" }, category: "Temperos e Especiarias", offers: { "@type": "Offer", url, priceCurrency: price.currencyCode, price: price.amount, availability: available ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", itemCondition: "https://schema.org/NewCondition" } }; const breadcrumbLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Início", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Sabores", item: `${SITE_URL}/produtos` }, { "@type": "ListItem", position: 3, name: p.title, item: url }] }; return { meta: [{ title: `${p.title} — Temperanzza | Condimentos de Minas Gerais` }, { name: "description", content: description }, { property: "og:title", content: `${p.title} — Temperanzza` }, { property: "og:description", content: description }, { property: "og:type", content: "product" }, { property: "og:url", content: url }, ...(image ? [{ property: "og:image", content: image }, { name: "twitter:card", content: "summary_large_image" }] : [])], links: [{ rel: "canonical", href: url }, ...(image ? [{ rel: "preload", as: "image" as const, href: image, fetchpriority: "high" }] : [])], scripts: [{ type: "application/ld+json", children: JSON.stringify(productLd) }, { type: "application/ld+json", children: JSON.stringify(breadcrumbLd) }] }; }, component: ProductPage, notFoundComponent: () => <StatePage title="Produto não encontrado" />, errorComponent: () => <StatePage title="Erro ao carregar" /> });
function StatePage({ title }: { title: string }) { return <div className="min-h-[60vh] bg-brand-paper grid place-items-center px-6 text-center"><div><h1 className="font-display text-4xl">{title}</h1><Link to="/produtos" className="mt-6 inline-block underline underline-offset-4">Voltar ao catálogo</Link></div></div>; }

function ProductPage() {
  const { handle } = Route.useParams(); const [qty, setQty] = useState(1); const [imgIdx, setImgIdx] = useState(0); const addItem = useCartStore((s) => s.addItem); const isLoading = useCartStore((s) => s.isLoading); const { data: product, isLoading: loadingProduct } = useQuery(productQueryOptions(handle));
  const { data: allProducts } = useQuery({ queryKey: ["shopify-products", 24], queryFn: async () => { const res = await storefrontApiRequest(STOREFRONT_QUERY, { first: 24, query: null }); return (res?.data?.products?.edges ?? []) as ShopifyProduct[]; } });
  useEffect(() => { if (!product) return; trackEvent("view_item", { currency: product.priceRange.minVariantPrice.currencyCode, value: parseFloat(product.priceRange.minVariantPrice.amount), items: [toAnalyticsItem({ handle, title: product.title, price: product.priceRange.minVariantPrice.amount })] }); }, [product, handle]);
  if (loadingProduct) return <div className="min-h-[60vh] grid place-items-center bg-brand-paper"><Loader2 className="h-7 w-7 animate-spin" /></div>; if (!product) return null;
  const variant = product.variants.edges[0]?.node; const images = product.images.edges; const mainImage = images[imgIdx]?.node ?? images[0]?.node; const mainImageResolution = resolveProductImage(handle, mainImage?.url); const tone = getFlavorTone(handle, product.title); const recipes = getRecipesByHandle(handle); const diet = getProductDiet(handle); const geometry = getProductStageGeometry(handle, "pdp");
  const handleAdd = async () => { if (!variant) return; await addItem({ product: { node: product }, variantId: variant.id, variantTitle: variant.title, price: variant.price, quantity: qty, selectedOptions: variant.selectedOptions || [] }); trackEvent("add_to_cart", { currency: variant.price.currencyCode, value: parseFloat(variant.price.amount) * qty, items: [toAnalyticsItem({ handle, title: product.title, price: variant.price.amount, quantity: qty })] }); toast.success(`${product.title} adicionado à sacola`); };

  return <div className="min-h-screen bg-brand-paper"><main className="page-shell py-6 sm:py-10 lg:py-14"><Link to="/produtos" className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-brand-ink/65 transition hover:text-brand-ink"><ArrowLeft className="h-4 w-4" /> Voltar aos sabores</Link><section className="grid items-start gap-8 lg:grid-cols-[1.08fr_.92fr] lg:gap-16">
    <div className="lg:sticky lg:top-24"><div className="product-stage relative min-h-[480px] overflow-hidden sm:min-h-[620px]" data-product-stage={handle} data-image-source={mainImageResolution.source} style={{ backgroundColor: tone.bg }}><div className={`absolute left-1/2 -translate-x-1/2 rounded-full bg-black/13 blur-xl ${geometry.shadowClass}`} aria-hidden="true" />{mainImageResolution.url && <img src={mainImageResolution.url} alt={mainImage?.altText || product.title} data-product-handle={handle} data-image-source={mainImageResolution.source} fetchPriority="high" decoding="async" className={`absolute inset-0 m-auto object-contain drop-shadow-[0_24px_26px_rgba(0,0,0,.17)] animate-product-enter ${geometry.imageClass}`} />}</div>
      {images.length > 1 && <div className="mt-4 flex gap-3 overflow-x-auto pb-2">{images.map((img, i) => { const resolved = resolveProductImage(handle, img.node.url); return <button key={img.node.url} onClick={() => setImgIdx(i)} aria-label={`Ver imagem ${i + 1}`} aria-pressed={i === imgIdx} className={`relative h-20 w-20 shrink-0 overflow-hidden rounded-2xl border bg-brand-cream transition ${i === imgIdx ? "border-brand-ink" : "border-brand-ink/10"}`}>{resolved.url && <img src={resolved.url} alt="" data-image-source={resolved.source} loading="lazy" className="absolute inset-0 m-auto h-[82%] w-[76%] object-contain" />}</button>; })}</div>}
    </div>
    <div className="py-2 lg:py-8"><span className="text-xs font-semibold uppercase tracking-[.24em] text-muted-foreground">Casa Temperanzza</span><h1 className="mt-3 font-display text-[clamp(3.25rem,6vw,6.5rem)] font-semibold leading-[.88] text-brand-ink">{product.title}</h1><p className="mt-6 text-3xl font-semibold text-brand-ink">{formatBRL(product.priceRange.minVariantPrice.amount, product.priceRange.minVariantPrice.currencyCode)}</p>{product.description && <p className="mt-7 max-w-xl whitespace-pre-line text-base leading-7 text-brand-ink/70 sm:text-lg sm:leading-8">{product.description}</p>}{variant?.title && variant.title !== "Default Title" && <div className="mt-8 rounded-2xl bg-brand-cream px-5 py-4"><span className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Tamanho</span><p className="mt-1 font-semibold">{variant.title}</p></div>}<div className="mt-9 flex flex-col gap-3 sm:flex-row"><div className="flex h-14 items-center justify-between rounded-full border border-brand-ink/15 bg-white sm:w-40"><Button variant="ghost" size="icon" className="h-12 w-12 rounded-full" onClick={() => setQty(Math.max(1, qty - 1))} aria-label="Diminuir quantidade"><Minus className="h-4 w-4" /></Button><span className="font-semibold">{qty}</span><Button variant="ghost" size="icon" className="h-12 w-12 rounded-full" onClick={() => setQty(qty + 1)} aria-label="Aumentar quantidade"><Plus className="h-4 w-4" /></Button></div><Button onClick={handleAdd} disabled={isLoading || !variant?.availableForSale} className="h-14 flex-1 rounded-full bg-brand-ink px-7 text-brand-paper hover:bg-brand-ink/90">{isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <><ShoppingBag className="mr-2 h-4 w-4" />Adicionar à sacola</>}</Button></div>{variant && !variant.availableForSale && <p className="mt-3 text-sm font-semibold">Esgotado no momento</p>}<p className="mt-5 text-xs leading-5 text-muted-foreground">Embalado lote a lote em Minas Gerais · Envio calculado no fechamento do pedido.</p>{allProducts && allProducts.length > 1 && <div className="mt-12"><FlavorTiles products={allProducts} currentHandle={handle} /></div>}</div>
  </section><div className="section-space"><ProductTrust handle={handle} title={product.title} />{allProducts && allProducts.length > 1 && <CombinaCom currentHandle={handle} products={allProducts} />}{(diet || recipes.length > 0) && <section className="mt-16 grid gap-8 lg:grid-cols-3 lg:mt-24">{diet && <div className="lg:col-span-2"><DietCompatibilityPanel diet={diet} /></div>}<aside className="rounded-[2rem] bg-brand-cream p-7 sm:p-8"><div className="flex items-center gap-2 text-muted-foreground"><BookOpen className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-[.18em]">Na Cozinha Temperanzza</span></div><h2 className="mt-4 font-display text-3xl font-semibold leading-tight">{recipes.length ? `Receitas com ${product.title}` : "Inspire sua próxima receita"}</h2><div className="mt-6 space-y-3">{recipes.slice(0, 4).map((r) => <Link key={r.slug} to="/cozinha/$slug" params={{ slug: r.slug }} search={{ refeicao: "", proteina: "", lifestyle: "", autor: "" }} className="block rounded-2xl bg-white/70 px-4 py-3 text-sm font-medium transition hover:bg-white">{r.title}</Link>)}</div><Link to="/cozinha" search={{ refeicao: "", proteina: "", lifestyle: "", autor: "" }} className="mt-7 inline-flex text-sm font-semibold underline underline-offset-4">Explorar todas as receitas</Link></aside></section>}</div></main></div>;
}
