import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { storefrontApiRequest, STOREFRONT_QUERY, type ShopifyProduct } from "@/lib/shopify";
import { ProductCard } from "./ProductCard";
import { Loader2, Search, X } from "lucide-react";
import { getProductDiet } from "@/lib/dietCompatibility";
import { DIETS, type DietKey } from "@/lib/diets";
import { hasConfirmedRebrandSource, isRebrandEligibleHandle } from "@/lib/rebrandCatalog";
import { resolveProductImage } from "@/lib/productImages";
type LinhaKey = "todas" | "temperaflix";
function isTemperaflix(handle: string) { return handle.startsWith("temperaflix-"); }
function hasIntegratedRebrandMaster(handle: string) { return hasConfirmedRebrandSource(handle) && resolveProductImage(handle).source === "rebrand"; }
interface CatalogGridProps { query?: string | null; excludeHandles?: string[]; }
export function CatalogGrid({ query = null, excludeHandles }: CatalogGridProps) {
 const [term,setTerm]=useState(""); const [linha,setLinha]=useState<LinhaKey>("todas"); const [diet,setDiet]=useState<DietKey|"todas">("todas");
 const {data,isLoading,error}=useQuery({queryKey:["catalog-grid",query,excludeHandles?.join(",")??""],queryFn:async()=>{const res=await storefrontApiRequest(STOREFRONT_QUERY,{first:50,query}); let edges=(res?.data?.products?.edges??[]) as ShopifyProduct[]; edges=edges.filter((e)=>isRebrandEligibleHandle(e.node.handle)&&hasIntegratedRebrandMaster(e.node.handle)); if(excludeHandles?.length){const ex=new Set(excludeHandles);edges=edges.filter((e)=>!ex.has(e.node.handle));} return edges;}});
 const lineCounts=useMemo(()=>({all:data?.length??0,temperaflix:data?.filter((p)=>isTemperaflix(p.node.handle)).length??0}),[data]);
 const lines=[{key:"todas" as const,label:"Toda a Casa",hint:`${lineCounts.all} sabores`},{key:"temperaflix" as const,label:"Temperaflix",hint:`${lineCounts.temperaflix} sabores`}];
 const filtered=useMemo(()=>{if(!data)return[];const t=term.trim().toLowerCase();return data.filter((p)=>{const h=p.node.handle,title=p.node.title.toLowerCase();if(t&&!title.includes(t)&&!h.includes(t))return false;if(linha==="temperaflix"&&!isTemperaflix(h))return false;if(diet!=="todas"){const verdict=getProductDiet(h)?.verdicts[diet]?.verdict;if(verdict==="no"||!verdict)return false;}return true;});},[data,term,linha,diet]);
 const active=(term?1:0)+(linha!=="todas"?1:0)+(diet!=="todas"?1:0); const clear=()=>{setTerm("");setLinha("todas");setDiet("todas");};
 if(isLoading)return <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-muted-foreground" /></div>; if(error)return <div className="py-20 text-center text-muted-foreground">Não foi possível carregar o catálogo agora.</div>;
 return <div><div className="mb-14 border-y border-brand-ink/10 py-6"><div className="grid gap-5 lg:grid-cols-[minmax(260px,.8fr)_1.2fr]"><div className="relative"><Search className="absolute left-0 top-1/2 h-4 w-4 -translate-y-1/2 text-brand-ink/40"/><input type="search" value={term} onChange={(e)=>setTerm(e.target.value)} placeholder="Buscar tempero…" aria-label="Buscar tempero pelo nome" className="h-12 w-full border-0 border-b border-brand-ink/20 bg-transparent pl-7 pr-8 text-base outline-none transition focus:border-brand-ink"/>{term&&<button onClick={()=>setTerm("")} aria-label="Limpar busca" className="absolute right-0 top-1/2 -translate-y-1/2"><X className="h-4 w-4"/></button>}</div><div className="flex flex-wrap items-center gap-2 lg:justify-end">{lines.map((l)=><button key={l.key} onClick={()=>setLinha(l.key)} aria-pressed={linha===l.key} className={`min-h-10 rounded-full border px-4 text-xs font-semibold transition ${linha===l.key?"border-brand-ink bg-brand-ink text-white":"border-brand-ink/15 hover:border-brand-ink/35"}`}>{l.label} <span className="ml-1 opacity-55">{l.hint}</span></button>)}<button onClick={()=>setDiet("todas")} aria-pressed={diet==="todas"} className={`min-h-10 rounded-full border px-4 text-xs font-semibold ${diet==="todas"?"border-brand-ink bg-brand-ink text-white":"border-brand-ink/15"}`}>Todas as dietas</button>{DIETS.map((d)=><button key={d.key} onClick={()=>setDiet(d.key)} aria-pressed={diet===d.key} className={`min-h-10 rounded-full border px-4 text-xs font-semibold ${diet===d.key?"border-brand-ink bg-brand-ink text-white":"border-brand-ink/15"}`}>{d.short}</button>)}</div></div><div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span>{filtered.length} {filtered.length===1?"tempero":"temperos"}</span>{active>0&&<button onClick={clear} className="inline-flex items-center gap-1 font-semibold text-brand-ink">Limpar filtros <X className="h-3 w-3"/></button>}</div></div>
 {filtered.length===0?<div className="py-20 text-center"><p className="font-display text-2xl">Nenhum tempero corresponde ao filtro.</p>{active>0&&<button onClick={clear} className="mt-5 border-b border-brand-ink/30 pb-1 text-sm font-semibold">Limpar filtros</button>}</div>:<div className="grid grid-cols-2 gap-x-5 gap-y-14 md:grid-cols-3 md:gap-x-8 lg:grid-cols-4 lg:gap-x-10 lg:gap-y-20">{filtered.map((p)=><ProductCard key={p.node.id} product={p}/>)}</div>}
 </div>;
}
