/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemperaflixRouteImport } from './routes/temperaflix'
import { Route as SuaCaixaRouteImport } from './routes/sua-caixa'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as EmbaixadoresRouteImport } from './routes/embaixadores'
import { Route as CozinhaRouteImport } from './routes/cozinha'
import { Route as ColaborarRouteImport } from './routes/colaborar'
import { Route as BlendsRouteImport } from './routes/blends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuaCaixaIndexRouteImport } from './routes/sua-caixa.index'
import { Route as CozinhaIndexRouteImport } from './routes/cozinha.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlendsIndexRouteImport } from './routes/blends.index'
import { Route as SuaCaixaSlugRouteImport } from './routes/sua-caixa.$slug'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as LegalTrocasRouteImport } from './routes/legal.trocas'
import { Route as LegalTermosRouteImport } from './routes/legal.termos'
import { Route as LegalPrivacidadeRouteImport } from './routes/legal.privacidade'
import { Route as ImprimirSlugRouteImport } from './routes/imprimir.$slug'
import { Route as CozinhaSlugRouteImport } from './routes/cozinha.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlendsSlugRouteImport } from './routes/blends.$slug'
import { Route as AdminBlingRouteImport } from './routes/admin.bling'
import { Route as ApiPublicShopifyOrderWebhookRouteImport } from './routes/api/public/shopify/order-webhook'
import { Route as ApiPublicBlingSyncRouteImport } from './routes/api/public/bling/sync'
import { Route as ApiPublicBlingStatusRouteImport } from './routes/api/public/bling/status'
import { Route as ApiPublicBlingDisconnectRouteImport } from './routes/api/public/bling/disconnect'
import { Route as ApiPublicBlingCronSyncRouteImport } from './routes/api/public/bling/cron-sync'
import { Route as ApiPublicBlingConnectRouteImport } from './routes/api/public/bling/connect'
import { Route as ApiPublicBlingCallbackRouteImport } from './routes/api/public/bling/callback'

const TemperaflixRoute = TemperaflixRouteImport.update({
  id: '/temperaflix',
  path: '/temperaflix',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaCaixaRoute = SuaCaixaRouteImport.update({
  id: '/sua-caixa',
  path: '/sua-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbaixadoresRoute = EmbaixadoresRouteImport.update({
  id: '/embaixadores',
  path: '/embaixadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaborarRoute = ColaborarRouteImport.update({
  id: '/colaborar',
  path: '/colaborar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlendsRoute = BlendsRouteImport.update({
  id: '/blends',
  path: '/blends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaCaixaIndexRoute = SuaCaixaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuaCaixaRoute,
} as any)
const CozinhaIndexRoute = CozinhaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CozinhaRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlendsIndexRoute = BlendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlendsRoute,
} as any)
const SuaCaixaSlugRoute = SuaCaixaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SuaCaixaRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTrocasRoute = LegalTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermosRoute = LegalTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacidadeRoute = LegalPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => LegalRoute,
} as any)
const ImprimirSlugRoute = ImprimirSlugRouteImport.update({
  id: '/imprimir/$slug',
  path: '/imprimir/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaSlugRoute = CozinhaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CozinhaRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlendsSlugRoute = BlendsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlendsRoute,
} as any)
const AdminBlingRoute = AdminBlingRouteImport.update({
  id: '/admin/bling',
  path: '/admin/bling',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyOrderWebhookRoute =
  ApiPublicShopifyOrderWebhookRouteImport.update({
    id: '/api/public/shopify/order-webhook',
    path: '/api/public/shopify/order-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlingSyncRoute = ApiPublicBlingSyncRouteImport.update({
  id: '/api/public/bling/sync',
  path: '/api/public/bling/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlingStatusRoute = ApiPublicBlingStatusRouteImport.update({
  id: '/api/public/bling/status',
  path: '/api/public/bling/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlingDisconnectRoute =
  ApiPublicBlingDisconnectRouteImport.update({
    id: '/api/public/bling/disconnect',
    path: '/api/public/bling/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlingCronSyncRoute = ApiPublicBlingCronSyncRouteImport.update({
  id: '/api/public/bling/cron-sync',
  path: '/api/public/bling/cron-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlingConnectRoute = ApiPublicBlingConnectRouteImport.update({
  id: '/api/public/bling/connect',
  path: '/api/public/bling/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlingCallbackRoute = ApiPublicBlingCallbackRouteImport.update({
  id: '/api/public/bling/callback',
  path: '/api/public/bling/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blends': typeof BlendsRouteWithChildren
  '/colaborar': typeof ColaborarRoute
  '/cozinha': typeof CozinhaRouteWithChildren
  '/embaixadores': typeof EmbaixadoresRoute
  '/legal': typeof LegalRouteWithChildren
  '/lojas': typeof LojasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/sua-caixa': typeof SuaCaixaRouteWithChildren
  '/temperaflix': typeof TemperaflixRoute
  '/admin/bling': typeof AdminBlingRoute
  '/blends/$slug': typeof BlendsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cozinha/$slug': typeof CozinhaSlugRoute
  '/imprimir/$slug': typeof ImprimirSlugRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/termos': typeof LegalTermosRoute
  '/legal/trocas': typeof LegalTrocasRoute
  '/product/$handle': typeof ProductHandleRoute
  '/sua-caixa/$slug': typeof SuaCaixaSlugRoute
  '/blends/': typeof BlendsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cozinha/': typeof CozinhaIndexRoute
  '/sua-caixa/': typeof SuaCaixaIndexRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/api/public/bling/connect': typeof ApiPublicBlingConnectRoute
  '/api/public/bling/cron-sync': typeof ApiPublicBlingCronSyncRoute
  '/api/public/bling/disconnect': typeof ApiPublicBlingDisconnectRoute
  '/api/public/bling/status': typeof ApiPublicBlingStatusRoute
  '/api/public/bling/sync': typeof ApiPublicBlingSyncRoute
  '/api/public/shopify/order-webhook': typeof ApiPublicShopifyOrderWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colaborar': typeof ColaborarRoute
  '/embaixadores': typeof EmbaixadoresRoute
  '/legal': typeof LegalRouteWithChildren
  '/lojas': typeof LojasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/temperaflix': typeof TemperaflixRoute
  '/admin/bling': typeof AdminBlingRoute
  '/blends/$slug': typeof BlendsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cozinha/$slug': typeof CozinhaSlugRoute
  '/imprimir/$slug': typeof ImprimirSlugRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/termos': typeof LegalTermosRoute
  '/legal/trocas': typeof LegalTrocasRoute
  '/product/$handle': typeof ProductHandleRoute
  '/sua-caixa/$slug': typeof SuaCaixaSlugRoute
  '/blends': typeof BlendsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cozinha': typeof CozinhaIndexRoute
  '/sua-caixa': typeof SuaCaixaIndexRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/api/public/bling/connect': typeof ApiPublicBlingConnectRoute
  '/api/public/bling/cron-sync': typeof ApiPublicBlingCronSyncRoute
  '/api/public/bling/disconnect': typeof ApiPublicBlingDisconnectRoute
  '/api/public/bling/status': typeof ApiPublicBlingStatusRoute
  '/api/public/bling/sync': typeof ApiPublicBlingSyncRoute
  '/api/public/shopify/order-webhook': typeof ApiPublicShopifyOrderWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blends': typeof BlendsRouteWithChildren
  '/colaborar': typeof ColaborarRoute
  '/cozinha': typeof CozinhaRouteWithChildren
  '/embaixadores': typeof EmbaixadoresRoute
  '/legal': typeof LegalRouteWithChildren
  '/lojas': typeof LojasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/sua-caixa': typeof SuaCaixaRouteWithChildren
  '/temperaflix': typeof TemperaflixRoute
  '/admin/bling': typeof AdminBlingRoute
  '/blends/$slug': typeof BlendsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cozinha/$slug': typeof CozinhaSlugRoute
  '/imprimir/$slug': typeof ImprimirSlugRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/termos': typeof LegalTermosRoute
  '/legal/trocas': typeof LegalTrocasRoute
  '/product/$handle': typeof ProductHandleRoute
  '/sua-caixa/$slug': typeof SuaCaixaSlugRoute
  '/blends/': typeof BlendsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cozinha/': typeof CozinhaIndexRoute
  '/sua-caixa/': typeof SuaCaixaIndexRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/api/public/bling/connect': typeof ApiPublicBlingConnectRoute
  '/api/public/bling/cron-sync': typeof ApiPublicBlingCronSyncRoute
  '/api/public/bling/disconnect': typeof ApiPublicBlingDisconnectRoute
  '/api/public/bling/status': typeof ApiPublicBlingStatusRoute
  '/api/public/bling/sync': typeof ApiPublicBlingSyncRoute
  '/api/public/shopify/order-webhook': typeof ApiPublicShopifyOrderWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blends'
    | '/colaborar'
    | '/cozinha'
    | '/embaixadores'
    | '/legal'
    | '/lojas'
    | '/produtos'
    | '/receitas'
    | '/sitemap.xml'
    | '/sobre'
    | '/sua-caixa'
    | '/temperaflix'
    | '/admin/bling'
    | '/blends/$slug'
    | '/blog/$slug'
    | '/cozinha/$slug'
    | '/imprimir/$slug'
    | '/legal/privacidade'
    | '/legal/termos'
    | '/legal/trocas'
    | '/product/$handle'
    | '/sua-caixa/$slug'
    | '/blends/'
    | '/blog/'
    | '/cozinha/'
    | '/sua-caixa/'
    | '/api/public/bling/callback'
    | '/api/public/bling/connect'
    | '/api/public/bling/cron-sync'
    | '/api/public/bling/disconnect'
    | '/api/public/bling/status'
    | '/api/public/bling/sync'
    | '/api/public/shopify/order-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colaborar'
    | '/embaixadores'
    | '/legal'
    | '/lojas'
    | '/produtos'
    | '/receitas'
    | '/sitemap.xml'
    | '/sobre'
    | '/temperaflix'
    | '/admin/bling'
    | '/blends/$slug'
    | '/blog/$slug'
    | '/cozinha/$slug'
    | '/imprimir/$slug'
    | '/legal/privacidade'
    | '/legal/termos'
    | '/legal/trocas'
    | '/product/$handle'
    | '/sua-caixa/$slug'
    | '/blends'
    | '/blog'
    | '/cozinha'
    | '/sua-caixa'
    | '/api/public/bling/callback'
    | '/api/public/bling/connect'
    | '/api/public/bling/cron-sync'
    | '/api/public/bling/disconnect'
    | '/api/public/bling/status'
    | '/api/public/bling/sync'
    | '/api/public/shopify/order-webhook'
  id:
    | '__root__'
    | '/'
    | '/blends'
    | '/colaborar'
    | '/cozinha'
    | '/embaixadores'
    | '/legal'
    | '/lojas'
    | '/produtos'
    | '/receitas'
    | '/sitemap.xml'
    | '/sobre'
    | '/sua-caixa'
    | '/temperaflix'
    | '/admin/bling'
    | '/blends/$slug'
    | '/blog/$slug'
    | '/cozinha/$slug'
    | '/imprimir/$slug'
    | '/legal/privacidade'
    | '/legal/termos'
    | '/legal/trocas'
    | '/product/$handle'
    | '/sua-caixa/$slug'
    | '/blends/'
    | '/blog/'
    | '/cozinha/'
    | '/sua-caixa/'
    | '/api/public/bling/callback'
    | '/api/public/bling/connect'
    | '/api/public/bling/cron-sync'
    | '/api/public/bling/disconnect'
    | '/api/public/bling/status'
    | '/api/public/bling/sync'
    | '/api/public/shopify/order-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlendsRoute: typeof BlendsRouteWithChildren
  ColaborarRoute: typeof ColaborarRoute
  CozinhaRoute: typeof CozinhaRouteWithChildren
  EmbaixadoresRoute: typeof EmbaixadoresRoute
  LegalRoute: typeof LegalRouteWithChildren
  LojasRoute: typeof LojasRoute
  ProdutosRoute: typeof ProdutosRoute
  ReceitasRoute: typeof ReceitasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SuaCaixaRoute: typeof SuaCaixaRouteWithChildren
  TemperaflixRoute: typeof TemperaflixRoute
  AdminBlingRoute: typeof AdminBlingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ImprimirSlugRoute: typeof ImprimirSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicBlingCallbackRoute: typeof ApiPublicBlingCallbackRoute
  ApiPublicBlingConnectRoute: typeof ApiPublicBlingConnectRoute
  ApiPublicBlingCronSyncRoute: typeof ApiPublicBlingCronSyncRoute
  ApiPublicBlingDisconnectRoute: typeof ApiPublicBlingDisconnectRoute
  ApiPublicBlingStatusRoute: typeof ApiPublicBlingStatusRoute
  ApiPublicBlingSyncRoute: typeof ApiPublicBlingSyncRoute
  ApiPublicShopifyOrderWebhookRoute: typeof ApiPublicShopifyOrderWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temperaflix': {
      id: '/temperaflix'
      path: '/temperaflix'
      fullPath: '/temperaflix'
      preLoaderRoute: typeof TemperaflixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-caixa': {
      id: '/sua-caixa'
      path: '/sua-caixa'
      fullPath: '/sua-caixa'
      preLoaderRoute: typeof SuaCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embaixadores': {
      id: '/embaixadores'
      path: '/embaixadores'
      fullPath: '/embaixadores'
      preLoaderRoute: typeof EmbaixadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborar': {
      id: '/colaborar'
      path: '/colaborar'
      fullPath: '/colaborar'
      preLoaderRoute: typeof ColaborarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blends': {
      id: '/blends'
      path: '/blends'
      fullPath: '/blends'
      preLoaderRoute: typeof BlendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-caixa/': {
      id: '/sua-caixa/'
      path: '/'
      fullPath: '/sua-caixa/'
      preLoaderRoute: typeof SuaCaixaIndexRouteImport
      parentRoute: typeof SuaCaixaRoute
    }
    '/cozinha/': {
      id: '/cozinha/'
      path: '/'
      fullPath: '/cozinha/'
      preLoaderRoute: typeof CozinhaIndexRouteImport
      parentRoute: typeof CozinhaRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blends/': {
      id: '/blends/'
      path: '/'
      fullPath: '/blends/'
      preLoaderRoute: typeof BlendsIndexRouteImport
      parentRoute: typeof BlendsRoute
    }
    '/sua-caixa/$slug': {
      id: '/sua-caixa/$slug'
      path: '/$slug'
      fullPath: '/sua-caixa/$slug'
      preLoaderRoute: typeof SuaCaixaSlugRouteImport
      parentRoute: typeof SuaCaixaRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/trocas': {
      id: '/legal/trocas'
      path: '/trocas'
      fullPath: '/legal/trocas'
      preLoaderRoute: typeof LegalTrocasRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/termos': {
      id: '/legal/termos'
      path: '/termos'
      fullPath: '/legal/termos'
      preLoaderRoute: typeof LegalTermosRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacidade': {
      id: '/legal/privacidade'
      path: '/privacidade'
      fullPath: '/legal/privacidade'
      preLoaderRoute: typeof LegalPrivacidadeRouteImport
      parentRoute: typeof LegalRoute
    }
    '/imprimir/$slug': {
      id: '/imprimir/$slug'
      path: '/imprimir/$slug'
      fullPath: '/imprimir/$slug'
      preLoaderRoute: typeof ImprimirSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha/$slug': {
      id: '/cozinha/$slug'
      path: '/$slug'
      fullPath: '/cozinha/$slug'
      preLoaderRoute: typeof CozinhaSlugRouteImport
      parentRoute: typeof CozinhaRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blends/$slug': {
      id: '/blends/$slug'
      path: '/$slug'
      fullPath: '/blends/$slug'
      preLoaderRoute: typeof BlendsSlugRouteImport
      parentRoute: typeof BlendsRoute
    }
    '/admin/bling': {
      id: '/admin/bling'
      path: '/admin/bling'
      fullPath: '/admin/bling'
      preLoaderRoute: typeof AdminBlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/order-webhook': {
      id: '/api/public/shopify/order-webhook'
      path: '/api/public/shopify/order-webhook'
      fullPath: '/api/public/shopify/order-webhook'
      preLoaderRoute: typeof ApiPublicShopifyOrderWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/sync': {
      id: '/api/public/bling/sync'
      path: '/api/public/bling/sync'
      fullPath: '/api/public/bling/sync'
      preLoaderRoute: typeof ApiPublicBlingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/status': {
      id: '/api/public/bling/status'
      path: '/api/public/bling/status'
      fullPath: '/api/public/bling/status'
      preLoaderRoute: typeof ApiPublicBlingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/disconnect': {
      id: '/api/public/bling/disconnect'
      path: '/api/public/bling/disconnect'
      fullPath: '/api/public/bling/disconnect'
      preLoaderRoute: typeof ApiPublicBlingDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/cron-sync': {
      id: '/api/public/bling/cron-sync'
      path: '/api/public/bling/cron-sync'
      fullPath: '/api/public/bling/cron-sync'
      preLoaderRoute: typeof ApiPublicBlingCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/connect': {
      id: '/api/public/bling/connect'
      path: '/api/public/bling/connect'
      fullPath: '/api/public/bling/connect'
      preLoaderRoute: typeof ApiPublicBlingConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/callback': {
      id: '/api/public/bling/callback'
      path: '/api/public/bling/callback'
      fullPath: '/api/public/bling/callback'
      preLoaderRoute: typeof ApiPublicBlingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlendsRouteChildren {
  BlendsSlugRoute: typeof BlendsSlugRoute
  BlendsIndexRoute: typeof BlendsIndexRoute
}

const BlendsRouteChildren: BlendsRouteChildren = {
  BlendsSlugRoute: BlendsSlugRoute,
  BlendsIndexRoute: BlendsIndexRoute,
}

const BlendsRouteWithChildren =
  BlendsRoute._addFileChildren(BlendsRouteChildren)

interface CozinhaRouteChildren {
  CozinhaSlugRoute: typeof CozinhaSlugRoute
  CozinhaIndexRoute: typeof CozinhaIndexRoute
}

const CozinhaRouteChildren: CozinhaRouteChildren = {
  CozinhaSlugRoute: CozinhaSlugRoute,
  CozinhaIndexRoute: CozinhaIndexRoute,
}

const CozinhaRouteWithChildren =
  CozinhaRoute._addFileChildren(CozinhaRouteChildren)

interface LegalRouteChildren {
  LegalPrivacidadeRoute: typeof LegalPrivacidadeRoute
  LegalTermosRoute: typeof LegalTermosRoute
  LegalTrocasRoute: typeof LegalTrocasRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacidadeRoute: LegalPrivacidadeRoute,
  LegalTermosRoute: LegalTermosRoute,
  LegalTrocasRoute: LegalTrocasRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface SuaCaixaRouteChildren {
  SuaCaixaSlugRoute: typeof SuaCaixaSlugRoute
  SuaCaixaIndexRoute: typeof SuaCaixaIndexRoute
}

const SuaCaixaRouteChildren: SuaCaixaRouteChildren = {
  SuaCaixaSlugRoute: SuaCaixaSlugRoute,
  SuaCaixaIndexRoute: SuaCaixaIndexRoute,
}

const SuaCaixaRouteWithChildren = SuaCaixaRoute._addFileChildren(
  SuaCaixaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlendsRoute: BlendsRouteWithChildren,
  ColaborarRoute: ColaborarRoute,
  CozinhaRoute: CozinhaRouteWithChildren,
  EmbaixadoresRoute: EmbaixadoresRoute,
  LegalRoute: LegalRouteWithChildren,
  LojasRoute: LojasRoute,
  ProdutosRoute: ProdutosRoute,
  ReceitasRoute: ReceitasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SuaCaixaRoute: SuaCaixaRouteWithChildren,
  TemperaflixRoute: TemperaflixRoute,
  AdminBlingRoute: AdminBlingRoute,
  BlogSlugRoute: BlogSlugRoute,
  ImprimirSlugRoute: ImprimirSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicBlingCallbackRoute: ApiPublicBlingCallbackRoute,
  ApiPublicBlingConnectRoute: ApiPublicBlingConnectRoute,
  ApiPublicBlingCronSyncRoute: ApiPublicBlingCronSyncRoute,
  ApiPublicBlingDisconnectRoute: ApiPublicBlingDisconnectRoute,
  ApiPublicBlingStatusRoute: ApiPublicBlingStatusRoute,
  ApiPublicBlingSyncRoute: ApiPublicBlingSyncRoute,
  ApiPublicShopifyOrderWebhookRoute: ApiPublicShopifyOrderWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
