// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/**
 * WHITELIST DE ROTAS PÚBLICAS
 * Estas rotas NÃO exigem autenticação Supabase
 */
const PUBLIC_ROUTES = [
  '/',                           // Home
  '/api/products',               // Catálogo público (GET)
  '/api/products/',              // Detalhe de produto
  '/api/cart',                   // Carrinho (GET)
  '/checkout',                   // Página checkout
  '/api/checkout',               // Processamento checkout
  '/confirmar',                  // Confirmação pedido
  '/api/order-confirmation',     // API confirmação
  '/receitas',                   // Receitas públicas
  '/api/recipes',                // API receitas
  '/sobre',                      // Sobre
  '/contato',                    // Contato
  '/api/contact',                // Envio de contato
];

/**
 * ROTAS QUE EXIGEM AUTENTICAÇÃO
 * Proteção ativa para admin e APIs privadas
 */
const PROTECTED_ROUTES = [
  '/admin',                      // Dashboard admin
  '/api/admin',                  // APIs administrativas
  '/api/bling',                  // Integração Bling (requer token Bling via server function)
  '/api/auth',                   // APIs de auth (excepto login/signup)
  '/perfil',                     // Perfil do usuário
  '/api/user',                   // APIs de usuário
];

/**
 * Verifica se a rota atual é pública
 */
function isPublicRoute(pathname: string): boolean {
  // Rotas exatas
  if (PUBLIC_ROUTES.includes(pathname)) {
    return true;
  }

  // Rotas com padrão dinâmico (ex: /api/products/123)
  if (pathname.startsWith('/api/products/') || pathname.startsWith('/receitas/')) {
    return true;
  }

  return false;
}

/**
 * Verifica se a rota exige autenticação
 */
function isProtectedRoute(pathname: string): boolean {
  return PROTECTED_ROUTES.some(route => pathname.startsWith(route));
}

/**
 * Extrai e valida o token do header Authorization
 */
function extractAndValidateToken(authHeader: string | null): { token: string; error: string | null } {
  if (!authHeader) {
    return { token: '', error: 'No authorization header provided' };
  }

  if (!authHeader.startsWith('Bearer ')) {
    return { token: '', error: 'Only Bearer tokens are supported' };
  }

  const token = authHeader.replace('Bearer ', '');
  if (!token) {
    return { token: '', error: 'No token provided' };
  }

  if (token.split('.').length !== 3) {
    return { token: '', error: 'Invalid token format' };
  }

  return { token, error: null };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabasePublishableKey = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!supabaseUrl || !supabasePublishableKey) {
      const missing = [
        ...(!supabaseUrl ? ['SUPABASE_URL'] : []),
        ...(!supabasePublishableKey ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();
    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const { token, error: tokenError } = extractAndValidateToken(
      request.headers.get('authorization'),
    );
    if (tokenError) {
      throw new Error(`Unauthorized: ${tokenError}`);
    }

    const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
      global: {
        fetch: createSupabaseFetch(supabasePublishableKey),
        headers: { Authorization: `Bearer ${token}` },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims?.sub) {
      throw new Error('Unauthorized: Invalid or expired token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
